const fs = require('fs');

// ALL missing Sinhala (si) keys identified by diff check
const si_missing = {
  "section_docs_title": "කොටස: ලේඛන සත්‍යාපනය",
  "lbl_mandatory_docs": "අනිවාර්ය ලේඛන",
  "msg_docs_desc": "ඉදිරිපත් කළ යුතු ලේඛනවල ඡේදනය ලේඛනය පිළිබඳ නිශ්චිත ඉල්ලීම් ශ්‍රේණිය:",
  "lbl_dynamic_docs": "ගතික ලේඛන ලැයිස්තුව",
  "lbl_discrepancy_affidavits": "විෂමතා ශකාව ලේඛනය",
  "msg_discrepancy_desc": "විෂමතා ශකාව ලේඛනය ඕනෑ නම් ඉදිරිපත් කරන්න",
  "lbl_affidavit_provided": "ශකාව ලේඛනය සපයා ඇත",
  "btn_calc_final_eligibility": "අවසාන සුදුසුකම ගණනය කරන්න",
  "section_f_ineligibility_title": "W&OP ප්‍රතිලාභ සඳහා සුදුසුකම් නොමැත",
  "msg_ineligibility_desc": "ඇතැම් සලකා බලීම් හේතුවෙන් ඔබගේ/ඔබේ මෙම ඉල්ලුම් W&OP ප්‍රතිලාභ සඳහා සුදුසු නොවේ.",
  "lbl_failure_identifiers": "ප්‍රතික්ෂේප කිරීමේ හේතු",
  "lbl_contributor": "දායකයා",
  "msg_not_captured": "ලබා ගත නොහැකි",
  "msg_rejection_trigger_info": "ප්‍රතික්ෂේප ඉල්ලීම් විස්තරය",
  "btn_back_correct_inputs": "ආපසු - ආදාන නිවැරදි කරන්න",
  "btn_acknowledge_exit": "තහවුරු කර ස්ක්‍රීනය සමාප්ත කරන්න",
  "section_f_eligibility_title": "W&OP {wopTitle} ප්‍රතිලාභ සඳහා සුදුසුකම් ඇත",
  "msg_validations_completed": "සියලු සත්‍යාපන සාර්ථකව සම්පූර්ණ කර ඇත.",
  "lbl_active_service_routing": "සක්‍රීය සේවය ලේඛනය",
  "lbl_payload_matrix": "ප්‍රතිලාභ බෙදාහැරීමේ මාත්‍රිකාව",
  "msg_0_allocation": "0% - සුදුසු ප්‍රතිලාභිකයන් නොමැත",
  "msg_no_eligible_desc": "සුදුසු ප්‍රතිලාභිකයන් හඳුනා ගත නොහැකි",
  "msg_100_allocation": "100% - ප්‍රතිලාභ සම්පූර්ණ",
  "msg_sole_orphan": "හුදකලා අනාථ දරුවා - 100% ලැබේ",
  "msg_eligible_orphans": "සුදුසු අනාථ දරුවන්",
  "msg_primary_deceased": "ප්‍රාථමික කලත්‍රයාගේ මරණය",
  "msg_primary_remarried": "ප්‍රාථමික කලත්‍රයා නැවත විවාහ වී ඇත",
  "msg_primary_abandoned": "ප්‍රාථමික කලත්‍රයා අතහැරීම",
  "msg_total_routes_sole": "ඒකීය ලාභිකයා - 100%",
  "msg_total_routes_multiple": "බහු ලාභිකයන් අතර බෙදී යයි",
  "msg_note_revert_50": "සටහන: ලාභිකයා 50% වෙත ආපසු",
  "msg_note_revert_100": "සටහන: ලාභිකයා 100% වෙත ආපසු",
  "msg_50_allocation_remarried": "50% - නැවත විවාහ කලත්‍රයා",
  "msg_remarried_desc": "නැවත විවාහ කලත්‍රයාගේ කොටස",
  "msg_50_allocation_spouse": "50% - ජීවතෙ කලත්‍රයා",
  "msg_spouse_50_desc": "ජීවතෙ කලත්‍රයාගේ 50% ලාභය",
  "msg_50_allocation_prior_orphans": "50% - පෙර විවාහයෙන් අනාථ දරුවන්",
  "msg_prior_orphans_desc": "පෙර විවාහ අනාථ දරු කොටස",
  "msg_100_allocation_spouse": "100% - ජීවතෙ කලත්‍රයා",
  "msg_spouse_100_desc": "ජීවතෙ කලත්‍රයා 100% ලාභය",
  "lbl_disabled_pension_auth": "ආබාධිත විශ්‍රාම අනුමැතිය",
  "lbl_dg_approval_req": "අධ්‍යක්ෂ ජනරාල් අනුමැතිය අවශ්‍ය",
  "msg_dg_approval_conditions": "පහත සඳහන් හේතූන් නිසා DG අනුමැතිය අවශ්‍ය:",
  "lbl_missing_docs_alert": "අනිවාර්ය ලේඛන අස්ථානගතය",
  "msg_missing_docs_desc": "ඉදිරිපත් නොකළ ලේඛන:",
  "msg_affidavit_supplied": "ශකාව ලේඛනය ලබා දී ඇත",
  "lbl_statutory_beneficiary_report": "ව්‍යවස්ථාමය ලාභිකයාගේ නිශ්චිත වාර්තාව",
  "th_beneficiary_class": "ලාභිකයාගේ පන්තිය",
  "th_name": "නම",
  "th_allocated_share": "නිශ්චිත කොටස",
  "th_reference_logic": "යොමු තර්කනය",
  "lbl_widow_remarried": "නැවත විවාහ වූ වැන්දඹු/වැන්දඹිය",
  "lbl_widow": "වැන්දඹු/වැන්දඹිය",
  "msg_remarriage_logged": "නැවත විවාහය ලේඛනගත කෙරේ",
  "lbl_validated_primary_spouse": "සත්‍යාපිත ප්‍රාථමික කලත්‍රයා",
  "msg_primary": "ප්‍රාථමික",
  "msg_remarriage_penalty": "නැවත විවාහ දඩය",
  "msg_distributed": "බෙදාහරිනු ලැබේ",
  "lbl_date_eligible": "සුදුසු දිනය",
  "lbl_invalid_date": "වලංගු නොවන දිනය",
  "msg_no_beneficiaries_identified": "සුදුසු ප්‍රතිලාභිකයන් හඳුනා නොගනී",
  "msg_no_prior_orphans": "පෙර විවාහ අනාථ දරුවන් නොමැත",
  "lbl_orphan": "අනාථ",
  "lbl_prior_orphan": "පෙර විවාහ අනාථ",
  "msg_lifetime_disabled": "ජීවිත කාලය පුරා ආබාධිත",
  "msg_guardian_intercepted": "භාරකාරු ලැබේ",
  "lbl_unnamed_child": "නම් නොකළ දරුවා",
  "msg_sole_beneficiary": "එකම ලාභිකයා",
  "msg_of_pool": "රැකවරණ ගිණුමෙන්",
  "lbl_from_marriage": "විවාහයෙන්",
  "lbl_age": "වයස",
  "lbl_status": "තත්ත්වය",
  "lbl_panel_validated": "පුවරු සත්‍යාපිතයි",
  "btn_print_eligibility": "සුදුසුකම් වාර්තාව මුද්‍රණය",
  "lbl_wop_system": "W&OP සුදුසුකම් - ඉදිරිපත් කිරීමේ ද්වාරය",
  "lbl_wop_pensions_division": "විශ්‍රාම වැටුප් දෙපාර්තමේන්තුව - වැන්දඹු සහ අනාථ විශ්‍රාම අංශය",
  "lbl_app_summary": "අයදුම් සාරාංශය",
  "lbl_ref": "යොමු: ",
  "lbl_generated": " | ජනනය: ",
  "lbl_section_a_summary": "කොටස A - සේවා සරාංශය",
  "lbl_benefit_type": "ප්‍රතිලාභ වර්ගය",
  "lbl_contributor_name": "දායකයාගේ නම",
  "msg_not_provided": "ලබා නොදී",
  "msg_missing_person_police": "නැතිවූ පුද්ගලයා | පොලිස් ස民원 දිනය: ",
  "lbl_service_status_death": "සේවා තත්ත්වය / මරණය",
  "msg_deceased_pensioner": "මිය ගිය විශ්‍රාමිකයා",
  "msg_deceased_in_service": "සේවයේ යෙදී සිටියදී මිය ගිය",
  "lbl_cabinet_date": "කැබිනට් අනුමත දිනය",
  "lbl_permanent_confirmed": "ස්ථිර සත්‍යාපිතය",
  "lbl_reckonable_service": "ගණනය කළ හැකි සේවා කාලය",
  "msg_years_months_days": "{y} වර්ෂ {m} මාස {d} දින",
  "lbl_wop_member_number": "W&OP සාමාජික අංකය",
  "lbl_registration_valid": "ලියාපදිංචිය වලංගු",
  "lbl_loss_of_pension_date": "විශ්‍රාම ලාභ නැති වූ දිනය",
  "msg_not_specified": "නිශ්චිත නොකෙරේ",
  "lbl_loss_of_pension_reason": "විශ්‍රාම ලාභ නැතිවීමේ හේතුව",
  "lbl_died_due_to_terrorism": "ත්‍රස්ත ක්‍රියා නිසා මිය ගිය",
  "lbl_no_contributor_marriages": "දායකයාගේ විවාහ ලේඛනගත නොකෙරේ",
  "lbl_marriage_dependants_summary": "විවාහ සහ යැපෙන්නන්ගේ සාරාංශය",
  "lbl_date_of_marriage": "විවාහ දිනය",
  "lbl_spouse_alive": "කලත්‍රයා ජීවතෙ",
  "lbl_termination": "විවාහ අවසන",
  "lbl_children_from_marriage": "විවාහයෙන් ලද දරුවන්",
  "th_dob": "ජන්ම දිනය",
  "th_occupation": "රැකියාව",
  "th_disabled": "ආබාධිත",
  "lbl_applicant_details": "අයදුම්කරුගේ විස්තර (වැන්දඹු/වැන්දඹිය)",
  "lbl_applicant_remarried": "අයදුම්කරු නැවත විවාහ වී ඇද?",
  "msg_date_na": "දිනය N/A",
  "lbl_applied_50_before_2014": "2014 ට පෙර 50% ඉල්ලා ඇද?",
  "lbl_uncountable_service_periods": "ගණනය නොකළ හැකි සේවා කාල",
  "th_from": "සිට",
  "th_to": "දක්වා",
  "th_reason": "හේතුව",
  "lbl_female_contributor_consent": "මහිළා දායකයා කැමැත්ත දිනය: ",
  "msg_pension_not_commenced_note": "සටහන: විශ්‍රාම ගෙවීම ආරම්භ නොවීය - PD 03 ද ඉදිරිපත් කළ යුතු",
  "lbl_required_docs_checklist": "අවශ්‍ය ලේඛන පිරික්සුම් ලැයිස්තුව",
  "lbl_verified": "සත්‍යාපිත",
  "lbl_document": "ලේඛනය",
  "msg_na": "N/A",
  "lbl_age_display": "වයස: {age}",
  "lbl_overpayment_summary": "අධිගෙවීම් සාරාංශය",
  "msg_overpayment_months": "අධිගෙවීමේ මාස {n}: {months} මාස",
  "btn_print_eligibility_determination": "සුදුසුකම් තීරණ වාර්තාව මුද්‍රණය",
  "lbl_service_sector": "සේවා අංශය",
  "opt_civil": "සිවිල්",
  "opt_forces": "හමුදා / ත්‍රිවිධ හමුදා",
  "lbl_service_category": "සේවා කාණ්ඩය",
  "opt_regular_force": "නිත්‍ය හමුදාව",
  "opt_volunteer_force": "ස්වේච්ඡා හමුදාව",
  "lbl_military_consent_date": "W&OP දායකත්ව කැමැත්ත දිනය",
  "lbl_retired_due_to_terrorism": "ත්‍රස්ත ක්‍රියා නිසා ආබාධිත ලෙස විශ්‍රාම ගත් ද?",
  "err_military_consent_missing": "W&OP දායකත්ව කැමැත්ත දිනය ඇතුළත් කරන්න",
  "err_military_consent_late_regular": "නිත්‍ය හමුදා W&OP: 30 ජූනි 2006 දේශසීමාව ඉක්මවා ඇත",
  "err_military_consent_late_volunteer": "ස්වේච්ඡා හමුදා W&OP: 31 දෙසැම්බර් 2012 දේශසීමාව ඉක්මවා ඇත"
};

const file = './src/locales/si.json';
let existing = {};
if (fs.existsSync(file)) {
  existing = JSON.parse(fs.readFileSync(file, 'utf8'));
}
const updated = { ...existing, ...si_missing };
fs.writeFileSync(file, JSON.stringify(updated, null, 2));
console.log('si.json updated with', Object.keys(si_missing).length, 'keys');
