const fs = require('fs');

const sec7_en = {
  "lbl_discrepancy_affidavits_validated": "✓ Discrepancy Affidavit(s) have been submitted and validated.",
  "lbl_missing_documents_count": "Missing Documents ({count}):",
  "lbl_eligibility_determination_report": "ELIGIBILITY DETERMINATION REPORT",
  "msg_report_auto_generated": "This report is auto-generated by the W&OP Eligibility Engine. This output serves as guidance only and does not constitute an official pension award. All information must be independently verified by the W&OP Pensions Division.",
  "lbl_role": " | Role: ",
  "lbl_benefit": " | Benefit: ",
  "lbl_member_no": " | Member No: ",
  "lbl_pension_distribution_determination": "Pension Distribution Determination",
  "lbl_distribution_scenario": "Distribution Scenario",
  "msg_100_to_widow": "100% to Widow/Widower",
  "msg_50_50_split_spouse_prior_orphans": "50/50 Split (Spouse + Prior Orphans)",
  "msg_50_remarried_widow": "50% to Remarried Widow/Widower",
  "msg_100_orphans_revert_50": "100% to Orphans (Reversion at 50%)",
  "msg_100_orphans_no_revert": "100% to Orphans (No Reversion)",
  "msg_100_orphans_revert_100": "100% to Orphans (Reversion at 100%)",
  "msg_no_eligible_beneficiaries": "No Eligible Beneficiaries",
  "lbl_widow_entitlement": "Widow/Widower Entitlement",
  "lbl_primary_spouse": "Primary Spouse",
  "msg_orphan_disabled": " (Disabled)",
  "msg_unnamed": "Unnamed",
  "lbl_missing_person_declaration": "Missing Person Declaration",
  "lbl_police_complaint": "Police Complaint: ",
  "lbl_dg_approval_required": "DG Approval Required",
  "lbl_death_gratuity_pd05": "Death Gratuity (PD 05)",
  "lbl_applicant_signature": "Applicant's Signature / Thumbprint",
  "lbl_date_line": "Date: _______________",
  "lbl_authorized_officer": "Authorized Officer",
  "lbl_stamp_date": "Stamp & Date: _______________"
};

const sec7_si = {
  "lbl_discrepancy_affidavits_validated": "✓ විෂමතා දිවුරුම් පෙත්සම(න්) ඉදිරිපත් කර සත්‍යාපනය කර ඇත.",
  "lbl_missing_documents_count": "අස්ථානගත වූ ලේඛන ({count}):",
  "lbl_eligibility_determination_report": "සුදුසුකම් තීරණය කිරීමේ වාර්තාව",
  "msg_report_auto_generated": "මෙම වාර්තාව W&OP සුදුසුකම් එන්ජිම මගින් ස්වයංක්‍රීයව ජනනය කෙරේ. මෙම ප්‍රතිදානය මාර්ගෝපදේශයක් ලෙස පමණක් ක්‍රියා කරන අතර නිල විශ්‍රාම වැටුප් ප්‍රදානයක් නොවේ. සියලුම තොරතුරු W&OP විශ්‍රාම වැටුප් අංශය විසින් ස්වාධීනව සත්‍යාපනය කළ යුතුය.",
  "lbl_role": " | කාර්යභාරය: ",
  "lbl_benefit": " | ප්‍රතිලාභය: ",
  "lbl_member_no": " | සාමාජික අංකය: ",
  "lbl_pension_distribution_determination": "විශ්‍රාම වැටුප් බෙදාහැරීමේ තීරණය",
  "lbl_distribution_scenario": "බෙදාහැරීමේ තත්ත්වය",
  "msg_100_to_widow": "100% ක් වැන්දඹුවට/වැන්දඹු පුරුෂයාට",
  "msg_50_50_split_spouse_prior_orphans": "50/50 බෙදීම (සහකරු + පෙර අනාථ දරුවන්)",
  "msg_50_remarried_widow": "50% ක් නැවත විවාහ වූ වැන්දඹුවට/වැන්දඹු පුරුෂයාට",
  "msg_100_orphans_revert_50": "100% ක් අනාථ දරුවන්ට (50% කින් ආපසු ලබා දීම)",
  "msg_100_orphans_no_revert": "100% ක් අනාථ දරුවන්ට (ආපසු ලබා දීමක් නැත)",
  "msg_100_orphans_revert_100": "100% ක් අනාථ දරුවන්ට (100% කින් ආපසු ලබා දීම)",
  "msg_no_eligible_beneficiaries": "සුදුසුකම් ලත් ප්‍රතිලාභීන් නොමැත",
  "lbl_widow_entitlement": "වැන්දඹු/වැන්දඹු පුරුෂ හිමිකම",
  "lbl_primary_spouse": "ප්‍රාථමික සහකරු",
  "msg_orphan_disabled": " (ආබාධිත)",
  "msg_unnamed": "නමක් නොමැති",
  "lbl_missing_person_declaration": "අතුරුදහන් වූ පුද්ගල ප්‍රකාශය",
  "lbl_police_complaint": "පොලිස් පැමිණිල්ල: ",
  "lbl_dg_approval_required": "අධ්‍යක්ෂ ජනරාල් අනුමැතිය අවශ්‍යයි",
  "lbl_death_gratuity_pd05": "මරණ පාරිතෝෂිකය (PD 05)",
  "lbl_applicant_signature": "අයදුම්කරුගේ අත්සන / මහපට ඇඟිලි සලකුණ",
  "lbl_date_line": "දිනය: _______________",
  "lbl_authorized_officer": "බලයලත් නිලධාරියා",
  "lbl_stamp_date": "මුද්‍රාව සහ දිනය: _______________"
};

const sec7_ta = {
  "lbl_discrepancy_affidavits_validated": "✓ முரண்பாட்டு சத்தியக்கடதாசிகள் சமர்ப்பிக்கப்பட்டு சரிபார்க்கப்பட்டுள்ளன.",
  "lbl_missing_documents_count": "காணாமல் போன ஆவணங்கள் ({count}):",
  "lbl_eligibility_determination_report": "தகுதி தீர்மான அறிக்கை",
  "msg_report_auto_generated": "இந்த அறிக்கை W&OP தகுதி இயந்திரத்தால் தானாக உருவாக்கப்படுகிறது. இந்த வெளியீடு வழிகாட்டுதலாக மட்டுமே செயல்படுகிறது மற்றும் இது உத்தியோகபூர்வ ஓய்வூதிய விருதை உருவாக்காது. அனைத்து தகவல்களும் W&OP ஓய்வூதிய பிரிவால் சுயாதீனமாக சரிபார்க்கப்பட வேண்டும்.",
  "lbl_role": " | பங்கு: ",
  "lbl_benefit": " | நன்மை: ",
  "lbl_member_no": " | உறுப்பினர் எண்: ",
  "lbl_pension_distribution_determination": "ஓய்வூதிய பகிர்ந்தளிப்பு தீர்மானம்",
  "lbl_distribution_scenario": "பகிர்ந்தளிப்பு காட்சி",
  "msg_100_to_widow": "100% விதவைக்கு/விதவை புருஷனுக்கு",
  "msg_50_50_split_spouse_prior_orphans": "50/50 பிளவு (துணை + முந்தைய அனாதைகள்)",
  "msg_50_remarried_widow": "50% மறுமணம் செய்த விதவைக்கு/விதவை புருஷனுக்கு",
  "msg_100_orphans_revert_50": "100% அனாதைகளுக்கு (50% மீளளிப்பு)",
  "msg_100_orphans_no_revert": "100% அனாதைகளுக்கு (மீளளிப்பு இல்லை)",
  "msg_100_orphans_revert_100": "100% அனாதைகளுக்கு (100% மீளளிப்பு)",
  "msg_no_eligible_beneficiaries": "தகுதியான பயனாளிகள் இல்லை",
  "lbl_widow_entitlement": "விதவை/விதவை புருஷன் உரிமை",
  "lbl_primary_spouse": "முதன்மை துணை",
  "msg_orphan_disabled": " (முடக்கப்பட்டவர்)",
  "msg_unnamed": "பெயரிடப்படாதவர்",
  "lbl_missing_person_declaration": "காணாமல் போனவர் அறிவிப்பு",
  "lbl_police_complaint": "பொலிஸ் முறைப்பாடு: ",
  "lbl_dg_approval_required": "பணிப்பாளர் நாயகத்தின் ஒப்புதல் தேவை",
  "lbl_death_gratuity_pd05": "இறப்புக் கொடை (PD 05)",
  "lbl_applicant_signature": "விண்ணப்பதாரரின் கையொப்பம் / கைரேகை",
  "lbl_date_line": "தேதி: _______________",
  "lbl_authorized_officer": "அங்கீகரிக்கப்பட்ட அதிகாரி",
  "lbl_stamp_date": "முத்திரை மற்றும் தேதி: _______________"
};


const newData = {
  en: { ...sec7_en },
  si: { ...sec7_si },
  ta: { ...sec7_ta }
};

['en', 'si', 'ta'].forEach(lang => {
  const file = `./src/locales/${lang}.json`;
  let existing = {};
  if(fs.existsSync(file)) {
      existing = JSON.parse(fs.readFileSync(file, 'utf8'));
  }
  const updated = { ...existing, ...newData[lang] };
  fs.writeFileSync(file, JSON.stringify(updated, null, 2));
});
