const fs = require('fs');

const sec6_en = {
  "lbl_wop_system": "Widows' & Orphans' Pension (W&OP) System",
  "lbl_wop_pensions_division": "W&OP Pensions Division — Department of Pensions",
  "lbl_app_summary": "APPLICATION SUMMARY",
  "lbl_ref": "Ref: ",
  "lbl_generated": " | Generated: ",
  "lbl_section_a_summary": "SECTION A: Entered Information Summary",
  "lbl_benefit_type": "Benefit Type",
  "lbl_contributor_name": "Contributor Name",
  "msg_not_provided": "Not Provided",
  "lbl_gender": "Gender",
  "lbl_dob": "Date of Birth",
  "lbl_dod": "Date of Death",
  "msg_missing_person_police": "Missing Person (Police: {date})",
  "lbl_service_status_death": "Service Status at Death",
  "msg_deceased_pensioner": "Deceased as a Pensioner",
  "msg_deceased_in_service": "Deceased while In Service",
  "lbl_dor": "Date of Retirement",
  "lbl_pension_commenced": "Pension Payments Commenced",
  "lbl_last_pension_date": "Last Pension Payment Date",
  "lbl_doa": "Date of Appointment",
  "lbl_cabinet_date": "Cabinet Date (Pre-1981)",
  "lbl_permanent_confirmed": "Permanent / Confirmed",
  "lbl_reckonable_service": "Reckonable Service",
  "msg_years_months_days": "{y} years, {m} months, {d} days",
  "lbl_wop_member_number": "W&OP Member Number",
  "lbl_registration_valid": "Registration Valid",
  "lbl_contributions_recovered": "Contributions Fully Recovered",
  "lbl_loss_of_pension_date": "Loss of Pension Date",
  "msg_not_specified": "Not Specified",
  "lbl_loss_of_pension_reason": "Loss of Pension Reason",
  "lbl_died_due_to_terrorism": "Died Due to Terrorism",
  "lbl_no_contributor_marriages": "No. of Contributor's Marriages",
  "lbl_marriage_dependants_summary": "Marriage & Dependants Summary",
  "lbl_date_of_marriage": "Date of Marriage",
  "lbl_spouse_name": "Spouse Name",
  "lbl_spouse_nic": "Spouse NIC",
  "lbl_spouse_alive": "Spouse Alive",
  "lbl_termination": "Termination",
  "lbl_children_from_marriage": "Children from this Marriage:",
  "th_dob": "DOB",
  "th_occupation": "Occupation",
  "th_disabled": "Disabled",
  "lbl_applicant_details": "Applicant (Widow/Widower) Details",
  "lbl_applicant_remarried": "Applicant Remarried",
  "msg_date_na": "Date N/A",
  "lbl_applied_50_before_2014": "Applied for 50% Pension Before 2014.12.31",
  "lbl_uncountable_service_periods": "Uncountable Service Periods:",
  "th_from": "From",
  "th_to": "To",
  "th_reason": "Reason",
  "lbl_female_contributor_consent": "Female Contributor Consent: ",
  "msg_pension_not_commenced_note": "Note: Pension payments had NOT commenced prior to demise.",
  "lbl_required_docs_checklist": "REQUIRED DOCUMENTS CHECKLIST",
  "lbl_verified": "Verified",
  "lbl_document": "Document",
  "msg_na": "N/A"
};

const sec6_si = {
  "lbl_wop_system": "වැන්දඹු සහ අනාථ විශ්‍රාම වැටුප් (W&OP) ක්‍රමය",
  "lbl_wop_pensions_division": "W&OP විශ්‍රාම වැටුප් අංශය - විශ්‍රාම වැටුප් දෙපාර්තමේන්තුව",
  "lbl_app_summary": "අයදුම්පත් සාරාංශය",
  "lbl_ref": "යොමුව: ",
  "lbl_generated": " | ජනනය කළේ: ",
  "lbl_section_a_summary": "A කොටස: ඇතුළත් කළ තොරතුරු සාරාංශය",
  "lbl_benefit_type": "ප්‍රතිලාභ වර්ගය",
  "lbl_contributor_name": "දායකයාගේ නම",
  "msg_not_provided": "සපයා නැත",
  "lbl_gender": "ස්ත්‍රී/පුරුෂ භාවය",
  "lbl_dob": "උපන් දිනය",
  "lbl_dod": "මියගිය දිනය",
  "msg_missing_person_police": "අතුරුදහන් වූවෙකි (පොලිසිය: {date})",
  "lbl_service_status_death": "මිය යන විට සේවා තත්ත්වය",
  "msg_deceased_pensioner": "විශ්‍රාමිකයෙකු ලෙස මියගොස් ඇත",
  "msg_deceased_in_service": "සේවයේ යෙදී සිටියදී මියගොස් ඇත",
  "lbl_dor": "විශ්‍රාම ගත් දිනය",
  "lbl_pension_commenced": "විශ්‍රාම වැටුප් ගෙවීම් ආරම්භ කර තිබේද",
  "lbl_last_pension_date": "අවසන් විශ්‍රාම වැටුප් ගෙවූ දිනය",
  "lbl_doa": "පත්වීම් දිනය",
  "lbl_cabinet_date": "කැබිනට් දිනය (1981ට පෙර)",
  "lbl_permanent_confirmed": "ස්ථිර/තහවුරු කළ",
  "lbl_reckonable_service": "ගණනය කළ හැකි සේවා කාලය",
  "msg_years_months_days": "වසර {y}, මාස {m}, දින {d}",
  "lbl_wop_member_number": "W&OP සාමාජික අංකය",
  "lbl_registration_valid": "ලියාපදිංචිය වලංගුයි",
  "lbl_contributions_recovered": "දායක මුදල් සම්පූර්ණයෙන්ම අයකරගෙන ඇත",
  "lbl_loss_of_pension_date": "විශ්‍රාම වැටුප අහිමි වූ දිනය",
  "msg_not_specified": "විශේෂයෙන් දක්වා නැත",
  "lbl_loss_of_pension_reason": "විශ්‍රාම වැටුප අහිමි වීමට හේතුව",
  "lbl_died_due_to_terrorism": "ත්‍රස්තවාදය හේතුවෙන් මියගොස් ඇත",
  "lbl_no_contributor_marriages": "දායකයාගේ විවාහ සංඛ්‍යාව",
  "lbl_marriage_dependants_summary": "විවාහ සහ යැපෙන්නන්ගේ සාරාංශය",
  "lbl_date_of_marriage": "විවාහ වූ දිනය",
  "lbl_spouse_name": "සහකරුගේ නම",
  "lbl_spouse_nic": "සහකරුගේ ජා.හැ.අ.",
  "lbl_spouse_alive": "සහකරු ජීවතුන් අතරද",
  "lbl_termination": "අවසන් වීම",
  "lbl_children_from_marriage": "මෙම විවාහයේ දරුවන්:",
  "th_dob": "උපන් දිනය",
  "th_occupation": "රැකියාව",
  "th_disabled": "ආබාධිත",
  "lbl_applicant_details": "අයදුම්කරු (වැන්දඹු/වැන්දඹු පුරුෂ) විස්තර",
  "lbl_applicant_remarried": "අයදුම්කරු නැවත විවාහ වී ඇත",
  "msg_date_na": "දිනය නොමැත",
  "lbl_applied_50_before_2014": "2014.12.31ට පෙර 50% විශ්‍රාම වැටුප සඳහා අයදුම් කර තිබේද",
  "lbl_uncountable_service_periods": "ගණනය කළ නොහැකි සේවා කාලයන්:",
  "th_from": "සිට",
  "th_to": "දක්වා",
  "th_reason": "හේතුව",
  "lbl_female_contributor_consent": "කාන්තා දායිකාවගේ කැමැත්ත: ",
  "msg_pension_not_commenced_note": "සටහන: මිය යාමට පෙර විශ්‍රාම වැටුප් ගෙවීම් ආරම්භ කර නොතිබුණි.",
  "lbl_required_docs_checklist": "අවශ්‍ය ලේඛන ලැයිස්තුව",
  "lbl_verified": "සත්‍යාපනය කර ඇත",
  "lbl_document": "ලේඛනය",
  "msg_na": "අදාළ නැත"
};

const sec6_ta = {
  "lbl_wop_system": "விதவைகள் மற்றும் அனாதைகள் ஓய்வூதிய (W&OP) முறைமை",
  "lbl_wop_pensions_division": "W&OP ஓய்வூதியப் பிரிவு - ஓய்வூதியத் திணைக்களம்",
  "lbl_app_summary": "விண்ணப்பச் சுருக்கம்",
  "lbl_ref": "குறிப்பு: ",
  "lbl_generated": " | உருவாக்கப்பட்டது: ",
  "lbl_section_a_summary": "பகுதி A: உள்ளிடப்பட்ட தகவல் சுருக்கம்",
  "lbl_benefit_type": "நன்மை வகை",
  "lbl_contributor_name": "பங்களிப்பாளர் பெயர்",
  "msg_not_provided": "வழங்கப்படவில்லை",
  "lbl_gender": "பாலினம்",
  "lbl_dob": "பிறந்த தேதி",
  "lbl_dod": "இறந்த தேதி",
  "msg_missing_person_police": "காணாமல் போனவர் (பொலிஸ்: {date})",
  "lbl_service_status_death": "இறக்கும் போது சேவை நிலை",
  "msg_deceased_pensioner": "ஓய்வூதியராக இறந்துள்ளார்",
  "msg_deceased_in_service": "சேவையில் இருக்கும்போது இறந்துள்ளார்",
  "lbl_dor": "ஓய்வு பெற்ற தேதி",
  "lbl_pension_commenced": "ஓய்வூதியக் கொடுப்பனவுகள் தொடங்கப்பட்டதா",
  "lbl_last_pension_date": "கடைசி ஓய்வூதியக் கொடுப்பனவுத் தேதி",
  "lbl_doa": "நியமனத் தேதி",
  "lbl_cabinet_date": "அமைச்சரவை தேதி (1981 க்கு முன்)",
  "lbl_permanent_confirmed": "நிரந்தர / உறுதிப்படுத்தப்பட்ட",
  "lbl_reckonable_service": "கணக்கிடக்கூடிய சேவை",
  "msg_years_months_days": "{y} ஆண்டுகள், {m} மாதங்கள், {d} நாட்கள்",
  "lbl_wop_member_number": "W&OP உறுப்பினர் எண்",
  "lbl_registration_valid": "பதிவு செல்லுபடியாகும்",
  "lbl_contributions_recovered": "பங்களிப்புகள் முழுமையாக அறவிடப்பட்டுள்ளன",
  "lbl_loss_of_pension_date": "ஓய்வூதியம் இழந்த தேதி",
  "msg_not_specified": "குறிப்பிடப்படவில்லை",
  "lbl_loss_of_pension_reason": "ஓய்வூதியம் இழந்தமைக்கான காரணம்",
  "lbl_died_due_to_terrorism": "பயங்கரவாதத்தால் இறந்துள்ளார்",
  "lbl_no_contributor_marriages": "பங்களிப்பாளரின் திருமணங்களின் எண்ணிக்கை",
  "lbl_marriage_dependants_summary": "திருமணம் மற்றும் சார்ந்திருப்போர் சுருக்கம்",
  "lbl_date_of_marriage": "திருமணத் தேதி",
  "lbl_spouse_name": "துணைவியின் பெயர்",
  "lbl_spouse_nic": "துணைவியின் தே.அ.அட்டை",
  "lbl_spouse_alive": "துணை உயிருடன் உள்ளாரா",
  "lbl_termination": "முடிவு",
  "lbl_children_from_marriage": "இந்த திருமணத்தின் குழந்தைகள்:",
  "th_dob": "பிறந்த தேதி",
  "th_occupation": "தொழில்",
  "th_disabled": "முடக்கப்பட்டவர்",
  "lbl_applicant_details": "விண்ணப்பதாரர் (விதவை/விதவை புருஷன்) விவரங்கள்",
  "lbl_applicant_remarried": "விண்ணப்பதாரர் மறுமணம் செய்துள்ளார்",
  "msg_date_na": "தேதி இல்லை",
  "lbl_applied_50_before_2014": "2014.12.31 க்கு முன் 50% ஓய்வூதியத்திற்கு விண்ணப்பிக்கப்பட்டதா",
  "lbl_uncountable_service_periods": "கணக்கிட முடியாத சேவை காலங்கள்:",
  "th_from": "இருந்து",
  "th_to": "வரை",
  "th_reason": "காரணம்",
  "lbl_female_contributor_consent": "பெண் பங்களிப்பாளர் சம்மதம்: ",
  "msg_pension_not_commenced_note": "குறிப்பு: இறப்பிற்கு முன் ஓய்வூதியக் கொடுப்பனவுகள் தொடங்கப்படவில்லை.",
  "lbl_required_docs_checklist": "தேவையான ஆவணங்களின் பட்டியல்",
  "lbl_verified": "சரிபார்க்கப்பட்டது",
  "lbl_document": "ஆவணம்",
  "msg_na": "இல்லை"
};

const newData = {
  en: { ...sec6_en },
  si: { ...sec6_si },
  ta: { ...sec6_ta }
};

['en', 'si', 'ta'].forEach(lang => {
  const file = `./src/locales/${lang}.json`;
  let existing = {};
  if(fs.existsSync(file)) {
      existing = JSON.parse(fs.readFileSync(file, 'utf8'));
  }
  const updated = { ...existing, ...newData[lang] };
  fs.writeFileSync(file, JSON.stringify(updated, null, 2));
});
