const fs = require('fs');

const sec5_en = {
  "section_docs_title": "Section: Document Verification",
  "lbl_mandatory_docs": "Mandatory Legal Document Verification",
  "msg_docs_desc": "Based on the specified profile, the following documents must be visually verified and validated. All birth/marriage/death certificates must be certified originals from the Additional/District Registrar.",
  "lbl_dynamic_docs": "Dynamically Required Documents",
  "lbl_discrepancy_affidavits": "Discrepancy Affidavits",
  "msg_discrepancy_desc": "If any name/dates or any other information discrepancies exist among documents, affidavit(s) must be submitted along with other documents declaring that those discrepancies belong to the single person.",
  "lbl_affidavit_provided": "Affidavit(s) verifying discrepancies has been officially submitted and validated.",
  "btn_calc_final_eligibility": "Calculate Final Eligibility",
  
  "section_f_ineligibility_title": "Section F: Final Ineligibility Report",
  "msg_ineligibility_desc": "The system has determined the requested inputs do not satisfy statutory W&OP requirements.",
  "lbl_failure_identifiers": "Failure Identifiers Generated",
  "lbl_contributor": "Contributor",
  "lbl_nic": "NIC",
  "msg_not_captured": "Not Captured",
  "msg_rejection_trigger_info": "If this rejection was triggered by accidental typographical errors across earlier input paths, please use the Back button to dynamically restructure the dates/properties correctly.",
  "btn_back_correct_inputs": "Back to Correct Inputs",
  "btn_acknowledge_exit": "Acknowledge and Exit",

  "section_f_eligibility_title": "Section F: Final Eligibility Output",
  "msg_validations_completed": "Based on the Provided Information, Validations have completed successfully.",
  "lbl_active_service_routing": "Active Service Benefit Routing",
  "lbl_payload_matrix": "W&OP Payload Distribution Matrix",
  "msg_0_allocation": "0% Allocation → No Eligible Beneficiaries",
  "msg_no_eligible_desc": "The primary legal spouse is deceased and there are no valid eligible orphans to inherit the pension.",
  "msg_100_allocation": "100% Allocation → ",
  "msg_sole_orphan": "Sole Eligible Orphan",
  "msg_eligible_orphans": "Eligible Orphans",
  "msg_primary_deceased": "The primary legal spouse is deceased.",
  "msg_primary_remarried": "The primary legal spouse has remarried.",
  "msg_primary_abandoned": "The primary legal spouse has abandoned care of orphans.",
  "msg_total_routes_sole": "The total pension routes to the sole eligible orphan.",
  "msg_total_routes_multiple": "The total pension routes to eligible orphans distributed equally",
  "msg_note_revert_50": "Note: Once all orphan eligibility expires, the remarried spouse may formally request reversion at 50%.",
  "msg_note_revert_100": "Note: Once all orphan eligibility expires, the spouse may formally request reversion at 100%.",
  "msg_50_allocation_remarried": "50% Allocation → Remarried Widow/Widower",
  "msg_remarried_desc": "The applicant widow/widower has remarried. No eligible orphans exist to receive the pension. Remarriage penalty reduces the entitlement to 50% of the original pension.",
  "msg_50_allocation_spouse": "50% Allocation → Active Legal Spouse",
  "msg_spouse_50_desc": "Primary widow(er) maintains their strict 50% legal entitlement.",
  "msg_50_allocation_prior_orphans": "50% Allocation → Prior Marriage Orphans",
  "msg_prior_orphans_desc": "The remaining 50% distributes equally among valid orphans originating from prior legally terminated marriages.",
  "msg_100_allocation_spouse": "100% Allocation → Active Legal Spouse",
  "msg_spouse_100_desc": "Primary widow(er) legally maintains absolute routing of the W&OP payload. Orphans from this current marriage are maintained by the spouse.",
  "lbl_disabled_pension_auth": "Disabled Pension Authorization:",
  "lbl_dg_approval_req": "Director General Approval Required",
  "msg_dg_approval_conditions": "The following conditions structurally necessitate Special Approval from the DG of Pensions dynamically bypassing general eligibility scopes:",
  "lbl_missing_docs_alert": "Mandatory Documents Missing",
  "msg_missing_docs_desc": "Logical Eligibility Status Achieved, but it is strictly mandatory to produce the relevant missing documents to claim the benefits:",
  "msg_affidavit_supplied": "Note: Affidavit supplied covering noted discrepancies.",
  "lbl_statutory_beneficiary_report": "Statutory Beneficiary Report",
  "th_beneficiary_class": "Beneficiary Class",
  "th_name": "Name",
  "th_allocated_share": "Allocated Share",
  "th_reference_logic": "Reference Logic",
  "lbl_widow_remarried": "Widow/Widower (Remarried)",
  "lbl_widow": "Widow/Widower",
  "msg_remarriage_logged": "(Remarriage Logged)",
  "lbl_validated_primary_spouse": "Validated Primary Spouse",
  "msg_primary": "Primary",
  "msg_remarriage_penalty": "(Remarriage Penalty)",
  "msg_distributed": "Distributed",
  "lbl_date_eligible": "Date Eligible: ",
  "lbl_invalid_date": "Invalid Date",
  "msg_no_beneficiaries_identified": "No eligible beneficiaries identified. Primary spouse is deceased and no valid orphans exist.",
  "msg_no_prior_orphans": "No eligible orphans from prior marriages.",
  "lbl_orphan": "Orphan",
  "lbl_prior_orphan": "Prior Orphan",
  "msg_lifetime_disabled": "- Lifetime Disabled Ext.",
  "msg_guardian_intercepted": "(Guardian Intercepted)",
  "lbl_unnamed_child": "Unnamed Child",
  "msg_sole_beneficiary": "(Sole Beneficiary)",
  "msg_of_pool": "(of {pool}% pool)",
  "lbl_from_marriage": "From Marriage ",
  "lbl_age": "Age: ",
  "lbl_status": "Status: ",
  "lbl_panel_validated": "Panel Validated: ",
  "btn_print_app_summary": "Print Application Summary",
  "btn_print_docs_list": "Print Documents List",
  "btn_print_eligibility": "Print Eligibility Output",
  "btn_return_dashboard": "Return to Portal Dashboard"
};

const sec5_si = {
  "section_docs_title": "කොටස: ලේඛන සත්‍යාපනය",
  "lbl_mandatory_docs": "අනිවාර්ය නීතිමය ලේඛන සත්‍යාපනය",
  "msg_docs_desc": "නිශ්චිත පැතිකඩ මත පදනම්ව, පහත ලේඛන දෘශ්‍යමය වශයෙන් සත්‍යාපනය කළ යුතුය. සියලුම උප්පැන්න/විවාහ/මරණ සහතික අතිරේක/දිස්ත්‍රික් රෙජිස්ට්‍රාර් වෙතින් සහතික කළ මුල් පිටපත් විය යුතුය.",
  "lbl_dynamic_docs": "අවශ්‍ය ලේඛන",
  "lbl_discrepancy_affidavits": "විෂමතා දිවුරුම් පෙත්සම්",
  "msg_discrepancy_desc": "ලේඛන අතර යම් නම්/දිනයන් හෝ වෙනත් තොරතුරු විෂමතා පවතී නම්, එම විෂමතා තනි පුද්ගලයාට අයත් බව ප්‍රකාශ කරමින් දිවුරුම් පෙත්සම් ඉදිරිපත් කළ යුතුය.",
  "lbl_affidavit_provided": "විෂමතා තහවුරු කරන දිවුරුම් පෙත්සම(න්) නිල වශයෙන් ඉදිරිපත් කර සත්‍යාපනය කර ඇත.",
  "btn_calc_final_eligibility": "අවසාන සුදුසුකම් ගණනය කරන්න",
  
  "section_f_ineligibility_title": "F කොටස: අවසාන නුසුදුසුකම් වාර්තාව",
  "msg_ineligibility_desc": "ඉල්ලා ඇති යෙදවුම් ව්‍යවස්ථාපිත W&OP අවශ්‍යතා සපුරාලන්නේ නැති බව පද්ධතිය තීරණය කර ඇත.",
  "lbl_failure_identifiers": "නිර්මාණය කරන ලද අසමත් හඳුනාගැනීම්",
  "lbl_contributor": "දායකයා",
  "lbl_nic": "ජාතික හැඳුනුම්පත",
  "msg_not_captured": "ග්‍රහණය කර නැත",
  "msg_rejection_trigger_info": "පෙර ආදාන මාර්ග හරහා අහඹු මුද්‍රණ දෝෂ මගින් මෙම ප්‍රතික්ෂේප කිරීම සිදුවූයේ නම්, කරුණාකර දිනයන්/ගුණාංග නිවැරදිව ප්‍රතිව්‍යුහගත කිරීමට Back බොත්තම භාවිතා කරන්න.",
  "btn_back_correct_inputs": "නිවැරදි යෙදවුම් වෙත ආපසු",
  "btn_acknowledge_exit": "පිළිගෙන පිටවන්න",

  "section_f_eligibility_title": "F කොටස: අවසාන සුදුසුකම් ප්‍රතිදානය",
  "msg_validations_completed": "සපයන ලද තොරතුරු මත පදනම්ව, සත්‍යාපනය සාර්ථකව අවසන් කර ඇත.",
  "lbl_active_service_routing": "සක්‍රීය සේවා ප්‍රතිලාභ මාර්ගගත කිරීම",
  "lbl_payload_matrix": "W&OP බෙදාහැරීමේ න්‍යාසය",
  "msg_0_allocation": "0% වෙන් කිරීම → සුදුසුකම් ලත් ප්‍රතිලාභීන් නොමැත",
  "msg_no_eligible_desc": "ප්‍රධාන නීත්‍යානුකූල සහකරු මියගොස් ඇති අතර විශ්‍රාම වැටුප උරුම කර ගැනීමට වලංගු සුදුසුකම් ලත් අනාථ දරුවන් නොමැත.",
  "msg_100_allocation": "100% වෙන් කිරීම → ",
  "msg_sole_orphan": "එකම සුදුසුකම් ලත් අනාථ දරුවා",
  "msg_eligible_orphans": "සුදුසුකම් ලත් අනාථ දරුවන්",
  "msg_primary_deceased": "ප්‍රධාන නීත්‍යානුකූල සහකරු මියගොස් ඇත.",
  "msg_primary_remarried": "ප්‍රධාන නීත්‍යානුකූල සහකරු නැවත විවාහ වී ඇත.",
  "msg_primary_abandoned": "ප්‍රධාන නීත්‍යානුකූල සහකරු අනාථ දරුවන් රැකබලා ගැනීම අතහැර දමා ඇත.",
  "msg_total_routes_sole": "මුළු විශ්‍රාම වැටුප එකම සුදුසුකම් ලත් අනාථ දරුවා වෙත යොමු කෙරේ.",
  "msg_total_routes_multiple": "මුළු විශ්‍රාම වැටුප සුදුසුකම් ලත් අනාථ දරුවන් අතර සමානව බෙදා හරිනු ලැබේ",
  "msg_note_revert_50": "සටහන: සියලුම අනාථ දරුවන්ගේ සුදුසුකම් කල් ඉකුත් වූ පසු, නැවත විවාහ වූ සහකරුට 50% කින් ආපසු ලබා දෙන ලෙස විධිමත්ව ඉල්ලා සිටිය හැකිය.",
  "msg_note_revert_100": "සටහන: සියලුම අනාථ දරුවන්ගේ සුදුසුකම් කල් ඉකුත් වූ පසු, සහකරුට 100% කින් ආපසු ලබා දෙන ලෙස විධිමත්ව ඉල්ලා සිටිය හැකිය.",
  "msg_50_allocation_remarried": "50% වෙන් කිරීම → නැවත විවාහ වූ වැන්දඹු/වැන්දඹු පුරුෂයා",
  "msg_remarried_desc": "අයදුම්කරු නැවත විවාහ වී ඇත. විශ්‍රාම වැටුප ලබා ගැනීමට සුදුසුකම් ලත් අනාථ දරුවන් නොමැත. නැවත විවාහ වීමේ දඩය හේතුවෙන් හිමිකම මුල් විශ්‍රාම වැටුපෙන් 50% දක්වා අඩු කරයි.",
  "msg_50_allocation_spouse": "50% වෙන් කිරීම → සක්‍රීය නීත්‍යානුකූල සහකරු",
  "msg_spouse_50_desc": "ප්‍රාථමික වැන්දඹුව ඔවුන්ගේ නීත්‍යානුකූල 50% හිමිකම පවත්වා ගනී.",
  "msg_50_allocation_prior_orphans": "50% වෙන් කිරීම → පෙර විවාහයේ අනාථ දරුවන්",
  "msg_prior_orphans_desc": "ඉතිරි 50% පෙර නීත්‍යානුකූලව අවසන් කරන ලද විවාහවලින් වලංගු අනාථ දරුවන් අතර සමානව බෙදා හරිනු ලැබේ.",
  "msg_100_allocation_spouse": "100% වෙන් කිරීම → සක්‍රීය නීත්‍යානුකූල සහකරු",
  "msg_spouse_100_desc": "ප්‍රාථමික වැන්දඹුව W&OP හි පූර්ණ හිමිකම නීත්‍යානුකූලව පවත්වා ගනී. මෙම වත්මන් විවාහයේ අනාථ දරුවන් සහකරු විසින් නඩත්තු කරනු ලැබේ.",
  "lbl_disabled_pension_auth": "ආබාධිත විශ්‍රාම වැටුප් අවසරය:",
  "lbl_dg_approval_req": "අධ්‍යක්ෂ ජනරාල් අනුමැතිය අවශ්‍යයි",
  "msg_dg_approval_conditions": "පහත සඳහන් කොන්දේසි හේතුවෙන් සාමාන්‍ය සුදුසුකම් විෂය පථයන් අභිබවා යමින් විශ්‍රාම වැටුප් අධ්‍යක්ෂ ජනරාල්වරයාගේ විශේෂ අනුමැතිය ව්‍යුහාත්මකව අවශ්‍ය වේ:",
  "lbl_missing_docs_alert": "අනිවාර්ය ලේඛන අස්ථානගත වී ඇත",
  "msg_missing_docs_desc": "තර්කානුකූලව සුදුසුකම් තත්ත්වය ලබාගෙන ඇත, නමුත් ප්‍රතිලාභ ඉල්ලා සිටීම සඳහා අදාළ අස්ථානගත වූ ලේඛන ඉදිරිපත් කිරීම අනිවාර්ය වේ:",
  "msg_affidavit_supplied": "සටහන: සටහන් කර ඇති විෂමතා ආවරණය කරමින් දිවුරුම් පෙත්සම සපයා ඇත.",
  "lbl_statutory_beneficiary_report": "ව්‍යවස්ථාපිත ප්‍රතිලාභී වාර්තාව",
  "th_beneficiary_class": "ප්‍රතිලාභී පන්තිය",
  "th_name": "නම",
  "th_allocated_share": "වෙන් කළ කොටස",
  "th_reference_logic": "යොමු තර්කනය",
  "lbl_widow_remarried": "වැන්දඹු/වැන්දඹු පුරුෂ (නැවත විවාහ වූ)",
  "lbl_widow": "වැන්දඹු/වැන්දඹු පුරුෂ",
  "msg_remarriage_logged": "(නැවත විවාහය සටහන් කර ඇත)",
  "lbl_validated_primary_spouse": "සත්‍යාපනය කළ ප්‍රාථමික සහකරු",
  "msg_primary": "ප්‍රාථමික",
  "msg_remarriage_penalty": "(නැවත විවාහ දඩය)",
  "msg_distributed": "බෙදාහරින ලද",
  "lbl_date_eligible": "සුදුසුකම් ලැබූ දිනය: ",
  "lbl_invalid_date": "අවලංගු දිනයකි",
  "msg_no_beneficiaries_identified": "සුදුසුකම් ලත් ප්‍රතිලාභීන් හඳුනාගෙන නොමැත. ප්‍රධාන සහකරු මියගොස් ඇති අතර වලංගු අනාථ දරුවන් නොමැත.",
  "msg_no_prior_orphans": "පෙර විවාහයන්ගෙන් සුදුසුකම් ලත් අනාථ දරුවන් නොමැත.",
  "lbl_orphan": "අනාථ දරුවා",
  "lbl_prior_orphan": "පෙර අනාථ දරුවා",
  "msg_lifetime_disabled": "- ජීවිත කාලය පුරා ආබාධිත",
  "msg_guardian_intercepted": "(භාරකරු හරහා)",
  "lbl_unnamed_child": "නමක් නොමැති දරුවා",
  "msg_sole_beneficiary": "(එකම ප්‍රතිලාභියා)",
  "msg_of_pool": "({pool}% සංචිතයෙන්)",
  "lbl_from_marriage": "විවාහයෙන් ",
  "lbl_age": "වයස: ",
  "lbl_status": "තත්ත්වය: ",
  "lbl_panel_validated": "මණ්ඩලය මගින් සත්‍යාපනය කළ: ",
  "btn_print_app_summary": "අයදුම්පත් සාරාංශය මුද්‍රණය කරන්න",
  "btn_print_docs_list": "ලේඛන ලැයිස්තුව මුද්‍රණය කරන්න",
  "btn_print_eligibility": "සුදුසුකම් ප්‍රතිදානය මුද්‍රණය කරන්න",
  "btn_return_dashboard": "ප්‍රධාන පිටුවට ආපසු යන්න"
};

const sec5_ta = {
  "section_docs_title": "பகுதி: ஆவண சரிபார்ப்பு",
  "lbl_mandatory_docs": "கட்டாய சட்ட ஆவண சரிபார்ப்பு",
  "msg_docs_desc": "குறிப்பிடப்பட்ட சுயவிவரத்தின் அடிப்படையில், பின்வரும் ஆவணங்கள் சரிபார்க்கப்பட வேண்டும். அனைத்து பிறப்பு/திருமண/இறப்புச் சான்றிதழ்களும் மேலதிக/மாவட்டப் பதிவாளரிடமிருந்து சான்றளிக்கப்பட்ட அசல்களாக இருக்க வேண்டும்.",
  "lbl_dynamic_docs": "தேவையான ஆவணங்கள்",
  "lbl_discrepancy_affidavits": "முரண்பாட்டு சத்தியக்கடதாசிகள்",
  "msg_discrepancy_desc": "ஆவணங்களுக்கிடையில் ஏதேனும் பெயர்/தேதி அல்லது பிற தகவல் முரண்பாடுகள் இருந்தால், அந்த முரண்பாடுகள் ஒரு நபருக்கு சொந்தமானவை என்று அறிவிக்கும் சத்தியக்கடதாசி சமர்ப்பிக்கப்பட வேண்டும்.",
  "lbl_affidavit_provided": "முரண்பாடுகளை சரிபார்க்கும் சத்தியக்கடதாசி அதிகாரபூர்வமாக சமர்ப்பிக்கப்பட்டு சரிபார்க்கப்பட்டுள்ளது.",
  "btn_calc_final_eligibility": "இறுதித் தகுதியைக் கணக்கிடு",
  
  "section_f_ineligibility_title": "பகுதி F: இறுதி தகுதியற்ற அறிக்கை",
  "msg_ineligibility_desc": "கோரப்பட்ட உள்ளீடுகள் சட்டரீதியான W&OP தேவைகளைப் பூர்த்தி செய்யவில்லை என கணினி தீர்மானித்துள்ளது.",
  "lbl_failure_identifiers": "உருவாக்கப்பட்ட தோல்வி அடையாளங்காட்டிகள்",
  "lbl_contributor": "பங்களிப்பாளர்",
  "lbl_nic": "தே.அ.அட்டை",
  "msg_not_captured": "கைப்பற்றப்படவில்லை",
  "msg_rejection_trigger_info": "இந்த நிராகரிப்பு முந்தைய உள்ளீட்டு வழிகளில் தற்செயலான அச்சுக்கலை பிழைகளால் தூண்டப்பட்டிருந்தால், தேதிகள்/பண்புகளை மாற்றி அமைக்க தயவுசெய்து Back பொத்தானைப் பயன்படுத்தவும்.",
  "btn_back_correct_inputs": "சரியான உள்ளீடுகளுக்குத் திரும்பு",
  "btn_acknowledge_exit": "ஏற்றுக்கொண்டு வெளியேறு",

  "section_f_eligibility_title": "பகுதி F: இறுதி தகுதி வெளியீடு",
  "msg_validations_completed": "வழங்கப்பட்ட தகவலின் அடிப்படையில், சரிபார்ப்புகள் வெற்றிகரமாக முடிந்துவிட்டன.",
  "lbl_active_service_routing": "செயலிலுள்ள சேவை நன்மை வழிப்படுத்துதல்",
  "lbl_payload_matrix": "W&OP பகிர்ந்தளிப்பு அணி",
  "msg_0_allocation": "0% ஒதுக்கீடு → தகுதியுள்ள பயனாளிகள் இல்லை",
  "msg_no_eligible_desc": "முதன்மை சட்டபூர்வ துணை இறந்துவிட்டார் மற்றும் ஓய்வூதியத்தை பெற தகுதியான அனாதைகள் எவரும் இல்லை.",
  "msg_100_allocation": "100% ஒதுக்கீடு → ",
  "msg_sole_orphan": "ஒரே தகுதியான அனாதை",
  "msg_eligible_orphans": "தகுதியான அனாதைகள்",
  "msg_primary_deceased": "முதன்மை சட்டபூர்வ துணை இறந்துவிட்டார்.",
  "msg_primary_remarried": "முதன்மை சட்டபூர்வ துணை மறுமணம் செய்துள்ளார்.",
  "msg_primary_abandoned": "முதன்மை சட்டபூர்வ துணை அனாதைகளை பராமரிப்பதை கைவிட்டுள்ளார்.",
  "msg_total_routes_sole": "மொத்த ஓய்வூதியமும் ஒரே தகுதியான அனாதைக்கு வழிப்படுத்தப்படுகிறது.",
  "msg_total_routes_multiple": "மொத்த ஓய்வூதியமும் தகுதியான அனாதைகளுக்கு சமமாகப் பகிரப்படுகிறது",
  "msg_note_revert_50": "குறிப்பு: அனாதைகளின் தகுதி காலாவதியானதும், மறுமணம் செய்த துணை 50% மீளளிக்க முறையாக கோரலாம்.",
  "msg_note_revert_100": "குறிப்பு: அனாதைகளின் தகுதி காலாவதியானதும், துணை 100% மீளளிக்க முறையாக கோரலாம்.",
  "msg_50_allocation_remarried": "50% ஒதுக்கீடு → மறுமணம் செய்த விதவை/விதவை புருஷன்",
  "msg_remarried_desc": "விண்ணப்பதாரர் மறுமணம் செய்துள்ளார். ஓய்வூதியத்தை பெற தகுதியான அனாதைகள் எவரும் இல்லை. மறுமண தண்டனை அசல் ஓய்வூதியத்தில் 50% ஆக குறைக்கிறது.",
  "msg_50_allocation_spouse": "50% ஒதுக்கீடு → செயலிலுள்ள சட்டபூர்வ துணை",
  "msg_spouse_50_desc": "முதன்மை விதவை தமது சட்டரீதியான 50% உரிமையை பராமரிக்கிறார்.",
  "msg_50_allocation_prior_orphans": "50% ஒதுக்கீடு → முந்தைய திருமண அனாதைகள்",
  "msg_prior_orphans_desc": "மீதமுள்ள 50% முந்தைய சட்டபூர்வ திருமணங்களிலிருந்து தகுதியான அனாதைகளுக்கு சமமாகப் பகிரப்படுகிறது.",
  "msg_100_allocation_spouse": "100% ஒதுக்கீடு → செயலிலுள்ள சட்டபூர்வ துணை",
  "msg_spouse_100_desc": "முதன்மை விதவை W&OP இன் முழு உரிமையையும் சட்டபூர்வமாக பராமரிக்கிறார். இந்த தற்போதைய திருமணத்தின் அனாதைகள் துணையால் பராமரிக்கப்படுகிறார்கள்.",
  "lbl_disabled_pension_auth": "முடக்கப்பட்ட ஓய்வூதிய அங்கீகாரம்:",
  "lbl_dg_approval_req": "பணிப்பாளர் நாயகத்தின் ஒப்புதல் தேவை",
  "msg_dg_approval_conditions": "பின்வரும் நிபந்தனைகள் காரணமாக பொதுவான தகுதி எல்லைகளை மீறி ஓய்வூதிய பணிப்பாளர் நாயகத்திடமிருந்து சிறப்பு ஒப்புதல் தேவைப்படுகிறது:",
  "lbl_missing_docs_alert": "கட்டாய ஆவணங்கள் காணவில்லை",
  "msg_missing_docs_desc": "தர்க்கரீதியான தகுதி நிலை அடையப்பட்டுள்ளது, ஆனால் நன்மைகளைப் பெற சம்பந்தப்பட்ட விடுபட்ட ஆவணங்களை சமர்ப்பிப்பது கட்டாயமாகும்:",
  "msg_affidavit_supplied": "குறிப்பு: குறிப்பிடப்பட்ட முரண்பாடுகளை உள்ளடக்கிய சத்தியக்கடதாசி வழங்கப்பட்டுள்ளது.",
  "lbl_statutory_beneficiary_report": "சட்டபூர்வ பயனாளி அறிக்கை",
  "th_beneficiary_class": "பயனாளி வகுப்பு",
  "th_name": "பெயர்",
  "th_allocated_share": "ஒதுக்கப்பட்ட பங்கு",
  "th_reference_logic": "குறிப்பு தர்க்கம்",
  "lbl_widow_remarried": "விதவை/விதவை புருஷன் (மறுமணம் செய்தவர்)",
  "lbl_widow": "விதவை/விதவை புருஷன்",
  "msg_remarriage_logged": "(மறுமணம் பதிவு செய்யப்பட்டுள்ளது)",
  "lbl_validated_primary_spouse": "சரிபார்க்கப்பட்ட முதன்மை துணை",
  "msg_primary": "முதன்மை",
  "msg_remarriage_penalty": "(மறுமண தண்டனை)",
  "msg_distributed": "பகிர்ந்தளிக்கப்பட்டது",
  "lbl_date_eligible": "தகுதியான தேதி: ",
  "lbl_invalid_date": "தவறான தேதி",
  "msg_no_beneficiaries_identified": "தகுதியான பயனாளிகள் கண்டறியப்படவில்லை. முதன்மை துணை இறந்துவிட்டார் மற்றும் தகுதியான அனாதைகள் இல்லை.",
  "msg_no_prior_orphans": "முந்தைய திருமணங்களிலிருந்து தகுதியான அனாதைகள் இல்லை.",
  "lbl_orphan": "அனாதை",
  "lbl_prior_orphan": "முந்தைய அனாதை",
  "msg_lifetime_disabled": "- ஆயுள் முழுவதும் முடக்கப்பட்டவர்",
  "msg_guardian_intercepted": "(பாதுகாவலர் மூலம்)",
  "lbl_unnamed_child": "பெயரிடப்படாத குழந்தை",
  "msg_sole_beneficiary": "(ஒரே பயனாளி)",
  "msg_of_pool": "({pool}% தொகுப்பிலிருந்து)",
  "lbl_from_marriage": "திருமணத்திலிருந்து ",
  "lbl_age": "வயது: ",
  "lbl_status": "நிலை: ",
  "lbl_panel_validated": "குழுவால் சரிபார்க்கப்பட்டது: ",
  "btn_print_app_summary": "விண்ணப்ப சுருக்கத்தை அச்சிடு",
  "btn_print_docs_list": "ஆவணங்களின் பட்டியலை அச்சிடு",
  "btn_print_eligibility": "தகுதி வெளியீட்டை அச்சிடு",
  "btn_return_dashboard": "முகப்புப் பக்கத்திற்குத் திரும்பு"
};

const newData = {
  en: { ...sec5_en },
  si: { ...sec5_si },
  ta: { ...sec5_ta }
};

['en', 'si', 'ta'].forEach(lang => {
  const file = `./src/locales/${lang}.json`;
  let existing = {};
  if(fs.existsSync(file)) {
      existing = JSON.parse(fs.readFileSync(file, 'utf8'));
  }
  const updated = { ...existing, ...newData[lang] };
  fs.writeFileSync(file, JSON.stringify(updated, null, 2));
});
