const fs = require('fs');

const secEF_en = {
  "section_e_title": "Section E: Applicant's Civil Status",
  "lbl_applicant_civil_status": "Applicant's Civil Status",
  "lbl_which_marriage_connects": "Which of these specific marriages logically connects to the deceased Contributor?",
  "lbl_marriage_idx": "Marriage ",
  "lbl_applicant_post_demise_status": "Applicant's Post-Demise Status",
  "lbl_applicant_engaged_another_marriage": "Has the final Applicant engaged in another legal marriage following the death of the Contributor?",
  "lbl_dependent_orphan_care": "Dependent Orphan Care Verification",
  "msg_no_eligible_orphans": "No legally eligible orphans computationally map to this framework.",
  "lbl_maintained_by_applicant": "Maintained by Applicant?",
  "msg_maintains_proxy": "(Maintains Proxy Status)",
  "msg_delegates_ownership": "(Delegates Ownership)",
  "msg_warning_validating_remarriage": "Warning: Validating Remarriage will statutorily deduct the final Widow/Widower payload strictly by 50% from this date forward.",
  "btn_proceed_docs": "Proceed to Document Verification",
  "err_applicant_marriage_post_ret": "Applicant Marriage fundamentally occurred post-retirement. Ineligible for W&OP.",
  "err_applicant_remarried_no_50": "Eligibility Denied: Applicant remarried prior to 2010.08.17 but failed to statutorily apply for the 50% pension before the deadline of 2014.12.31.",
  "err_divorced_from_contributor": "Eligibility Denied: Documented divorce from Contributor prior to demise. (Note: Valid associated orphans explicitly maintain 100% respective eligibility).",
  "err_format_red_fields": "Format Error: Please review the RED bordered fields to resolve structural errors before submitting.",
  
  "section_f_disabled_title": "Section F: Disabled Pension Intercept",
  "msg_no_disabled_orphans": "No Valid Disabled Orphans systematically detected in the data stream.",
  "section_f_disabled_eval_title": "Section F: Disabled Orphans Financial Profiling",
  "lbl_disabled_eval": "Disabled Dependent Evaluation",
  "msg_disabled_statutory_mandates": "Statutory mandates require absolute validation regarding independent income streams generated by adult disabled orphans claiming Lifetime Extensions.",
  "lbl_unnamed_dependent": "Unnamed Dependent",
  "lbl_disabled_possess_income": "Does this dependent personally possess independent earning capacity, direct income sources, or income-generating assets?",
  "lbl_provide_absolute_details": "Provide Absolute Details & Sources governing the Financial Capacity",
  "ph_list_specific_assets": "List specific bank assets, property revenue, independent business holdings, etc.",
  "msg_warning_independent_assets": "Warning: The explicit presence of independent assets overrides automatic pension deployment, forcing rigorous physical Verification & Absolute Approval routing directly administered structurally bypassing standard logic flows through the Director General.",
  "err_financial_dec_required": "Financial Declarations Required: Please explicitly document the nature of the assets for any Disabled Dependent tagged with Independent Generating Capacity."
};

const secEF_si = {
  "section_e_title": "E කොටස: අයදුම්කරුගේ සිවිල් තත්ත්වය",
  "lbl_applicant_civil_status": "අයදුම්කරුගේ සිවිල් තත්ත්වය",
  "lbl_which_marriage_connects": "මෙම විවාහයන්ගෙන් මියගිය දායකයාට තර්කානුකූලව සම්බන්ධ වන්නේ කුමන විවාහයද?",
  "lbl_marriage_idx": "විවාහය ",
  "lbl_applicant_post_demise_status": "මරණයෙන් පසු අයදුම්කරුගේ තත්ත්වය",
  "lbl_applicant_engaged_another_marriage": "දායකයාගේ මරණයෙන් පසු අවසන් අයදුම්කරු වෙනත් නීත්‍යානුකූල විවාහයකට එළඹී තිබේද?",
  "lbl_dependent_orphan_care": "යැපෙන අනාථ දරුවන් රැකබලා ගැනීමේ තහවුරුව",
  "msg_no_eligible_orphans": "මෙම රාමුවට අනුරූප වන නීත්‍යානුකූලව සුදුසුකම් ලත් අනාථ දරුවන් කිසිවෙක් නොමැත.",
  "lbl_maintained_by_applicant": "අයදුම්කරු විසින් නඩත්තු කරන්නේද?",
  "msg_maintains_proxy": "(නියෝජිත තත්ත්වය පවත්වා ගනී)",
  "msg_delegates_ownership": "(හිමිකාරිත්වය පවරා දෙයි)",
  "msg_warning_validating_remarriage": "අවවාදයයි: නැවත විවාහ වීම තහවුරු කිරීම මගින් මෙම දිනයේ සිට අවසාන වැන්දඹු/වැන්දඹු පුරුෂ ප්‍රතිලාභය ව්‍යවස්ථාපිතව 50% කින් අඩු කරනු ඇත.",
  "btn_proceed_docs": "ලේඛන සත්‍යාපනය වෙත යන්න",
  "err_applicant_marriage_post_ret": "අයදුම්කරුගේ විවාහය විශ්‍රාම ගැනීමෙන් පසුව සිදුවී ඇත. W&OP සඳහා සුදුසුකම් නොලබයි.",
  "err_applicant_remarried_no_50": "සුදුසුකම් ප්‍රතික්ෂේප කරන ලදී: අයදුම්කරු 2010.08.17 ට පෙර නැවත විවාහ වී ඇති නමුත් 2014.12.31 දිනට පෙර 50% විශ්‍රාම වැටුප සඳහා ව්‍යවස්ථාපිතව අයදුම් කිරීමට අපොහොසත් වී ඇත.",
  "err_divorced_from_contributor": "සුදුසුකම් ප්‍රතික්ෂේප කරන ලදී: මරණයට පෙර දායකයාගෙන් නීත්‍යානුකූලව දික්කසාද වී ඇත. (සටහන: වලංගු ආශ්‍රිත අනාථ දරුවන්ට 100% අදාළ සුදුසුකම පැහැදිලිවම පවත්වා ගනී).",
  "err_format_red_fields": "ආකෘති දෝෂය: කරුණාකර ඉදිරිපත් කිරීමට පෙර ව්‍යුහාත්මක දෝෂ නිරාකරණය කිරීම සඳහා රතු මායිම් සහිත ක්ෂේත්‍ර සමාලෝචනය කරන්න.",
  
  "section_f_disabled_title": "F කොටස: ආබාධිත විශ්‍රාම වැටුප් අතුරු තහනම් කිරීම",
  "msg_no_disabled_orphans": "දත්ත ප්‍රවාහය තුළ වලංගු ආබාධිත අනාථ දරුවන් කිසිවෙක් ක්‍රමානුකූලව අනාවරණය වී නොමැත.",
  "section_f_disabled_eval_title": "F කොටස: ආබාධිත අනාථ දරුවන්ගේ මූල්‍ය පැතිකඩ",
  "lbl_disabled_eval": "ආබාධිත යැපෙන්නන් ඇගයීම",
  "msg_disabled_statutory_mandates": "ජීවිත කාලය පුරාම දිගු කිරීම් ඉල්ලා සිටින වැඩිහිටි ආබාධිත අනාථ දරුවන් විසින් ජනනය කරන ස්වාධීන ආදායම් මාර්ග සම්බන්ධයෙන් නිරපේක්ෂ සත්‍යාපනයක් ව්‍යවස්ථාපිත විධාන මගින් අවශ්‍ය වේ.",
  "lbl_unnamed_dependent": "නමක් නොමැති යැපෙන්නා",
  "lbl_disabled_possess_income": "මෙම යැපෙන්නාට පෞද්ගලිකව ස්වාධීන ඉපැයීමේ හැකියාවක්, සෘජු ආදායම් මාර්ග හෝ ආදායම් උත්පාදනය කරන වත්කම් තිබේද?",
  "lbl_provide_absolute_details": "මූල්‍ය ධාරිතාව පාලනය කරන නිරපේක්ෂ තොරතුරු සහ මූලාශ්‍ර සපයන්න",
  "ph_list_specific_assets": "නිශ්චිත බැංකු වත්කම්, දේපල ආදායම්, ස්වාධීන ව්‍යාපාරික වත්කම් යනාදිය ලැයිස්තුගත කරන්න.",
  "msg_warning_independent_assets": "අවවාදයයි: ස්වාධීන වත්කම් පැහැදිලිවම පැවතීම මගින් ස්වයංක්‍රීය විශ්‍රාම වැටුප් යෙදවීම අභිබවා යයි, එමගින් අධ්‍යක්ෂ ජනරාල් හරහා සාමාන්‍ය තර්කන ප්‍රවාහයන් ව්‍යුහාත්මකව මගහරිමින් දැඩි භෞතික සත්‍යාපනය සහ නිරපේක්ෂ අනුමැතිය ලබාදීමක් බලහත්කාරයෙන් සිදුකරයි.",
  "err_financial_dec_required": "මූල්‍ය ප්‍රකාශන අවශ්‍යයි: කරුණාකර ස්වාධීන උත්පාදන ධාරිතාවක් ඇතැයි සලකුණු කර ඇති ඕනෑම ආබාධිත යැපෙන්නෙකු සඳහා වත්කම්වල ස්වභාවය පැහැදිලිව ලේඛනගත කරන්න."
};

const secEF_ta = {
  "section_e_title": "பகுதி E: விண்ணப்பதாரரின் சிவில் நிலை",
  "lbl_applicant_civil_status": "விண்ணப்பதாரரின் சிவில் நிலை",
  "lbl_which_marriage_connects": "இந்தத் திருமணங்களில் இறந்த பங்களிப்பாளருடன் எது தர்க்கரீதியாக இணைக்கப்பட்டுள்ளது?",
  "lbl_marriage_idx": "திருமணம் ",
  "lbl_applicant_post_demise_status": "இறப்பிற்குப் பின் விண்ணப்பதாரரின் நிலை",
  "lbl_applicant_engaged_another_marriage": "பங்களிப்பாளரின் இறப்பிற்குப் பிறகு இறுதி விண்ணப்பதாரர் வேறு சட்டபூர்வமான திருமணத்தில் ஈடுபட்டுள்ளாரா?",
  "lbl_dependent_orphan_care": "தங்கியிருக்கும் அனாதை பராமரிப்பு சரிபார்ப்பு",
  "msg_no_eligible_orphans": "இந்த கட்டமைப்புடன் தர்க்கரீதியாக இணைக்கப்படும் தகுதியுடைய அனாதைகள் எவரும் இல்லை.",
  "lbl_maintained_by_applicant": "விண்ணப்பதாரரால் பராமரிக்கப்படுகிறதா?",
  "msg_maintains_proxy": "(பிரதிநிதி நிலையை பராமரிக்கிறது)",
  "msg_delegates_ownership": "(உரிமையை வழங்குகிறது)",
  "msg_warning_validating_remarriage": "எச்சரிக்கை: மறுமணத்தை உறுதிப்படுத்துவது இந்த தேதியிலிருந்து இறுதி விதவை/விதவை நன்மையை 50% குறைக்கும்.",
  "btn_proceed_docs": "ஆவண சரிபார்ப்பிற்குச் செல்லவும்",
  "err_applicant_marriage_post_ret": "விண்ணப்பதாரர் திருமணம் ஓய்வுக்குப் பிறகு நடந்துள்ளது. W&OP கிடைக்காது.",
  "err_applicant_remarried_no_50": "தகுதி நிராகரிக்கப்பட்டது: விண்ணப்பதாரர் 2010.08.17 க்கு முன் மறுமணம் செய்துள்ளார், ஆனால் 2014.12.31 க்கு முன் 50% ஓய்வூதியத்திற்கு விண்ணப்பிக்கத் தவறிவிட்டார்.",
  "err_divorced_from_contributor": "தகுதி நிராகரிக்கப்பட்டது: இறப்பிற்கு முன் பங்களிப்பாளரிடமிருந்து விவாகரத்து செய்யப்பட்டுள்ளது. (குறிப்பு: செல்லுபடியாகும் அனாதைகளுக்கு 100% தகுதி பாதுகாக்கப்படுகிறது).",
  "err_format_red_fields": "வடிவமைப்பு பிழை: தயவுசெய்து சமர்ப்பிப்பதற்கு முன் பிழைகளைத் தீர்க்க சிவப்பு நிறக் கட்டங்களைக் கொண்ட புலங்களை மதிப்பாய்வு செய்யவும்.",
  
  "section_f_disabled_title": "பகுதி F: முடக்கப்பட்ட ஓய்வூதிய இடைமறிப்பு",
  "msg_no_disabled_orphans": "தரவு அமைப்பில் செல்லுபடியாகும் முடக்கப்பட்ட அனாதைகள் எவரும் இல்லை.",
  "section_f_disabled_eval_title": "பகுதி F: முடக்கப்பட்ட அனாதைகளின் நிதி சுயவிவரம்",
  "lbl_disabled_eval": "முடக்கப்பட்ட சார்ந்திருப்போர் மதிப்பீடு",
  "msg_disabled_statutory_mandates": "ஆயுள் நீட்டிப்புகளைக் கோரும் வயது வந்த முடக்கப்பட்ட அனாதைகளால் உருவாக்கப்படும் சுயாதீன வருமான ஆதாரங்கள் குறித்த முழுமையான சரிபார்ப்பை சட்டரீதியான அறிவுறுத்தல்கள் கோருகின்றன.",
  "lbl_unnamed_dependent": "பெயரிடப்படாத சார்ந்திருப்பவர்",
  "lbl_disabled_possess_income": "இந்தச் சார்ந்திருப்பவருக்கு தனிப்பட்ட வருமானம் ஈட்டும் திறன், நேரடி வருமான ஆதாரங்கள் அல்லது வருமானம் உருவாக்கும் சொத்துகள் உள்ளதா?",
  "lbl_provide_absolute_details": "நிதித் திறனை நிர்வகிக்கும் முழுமையான விவரங்கள் மற்றும் ஆதாரங்களை வழங்கவும்",
  "ph_list_specific_assets": "குறிப்பிட்ட வங்கி சொத்துகள், சொத்து வருவாய், சுயாதீன வணிக உடைமைகள் போன்றவற்றை பட்டியலிடுக.",
  "msg_warning_independent_assets": "எச்சரிக்கை: சுயாதீனமான சொத்துகளின் இருப்பு, தானியங்கி ஓய்வூதியத்தை மீறுகிறது, இது ஓய்வூதிய பணிப்பாளர் நாயகம் மூலம் நேரடி சரிபார்ப்பைக் கோருகிறது.",
  "err_financial_dec_required": "நிதி அறிவிப்புகள் தேவை: சுயாதீன வருமானம் ஈட்டும் திறன் உள்ளதாகக் குறிக்கப்பட்ட முடக்கப்பட்ட சார்ந்திருப்பவர்களின் சொத்துகளின் தன்மையைப் பதிவு செய்யவும்."
};

const newData = {
  en: { ...secEF_en },
  si: { ...secEF_si },
  ta: { ...secEF_ta }
};

['en', 'si', 'ta'].forEach(lang => {
  const file = `./src/locales/${lang}.json`;
  let existing = {};
  if(fs.existsSync(file)) {
      existing = JSON.parse(fs.readFileSync(file, 'utf8'));
  }
  const updated = { ...existing, ...newData[lang] };
  fs.writeFileSync(file, JSON.stringify(updated, null, 2));
});
