const fs = require('fs');

const secD_en = {
  "section_d_title": "Section D: Contributor's Civil Status",
  "lbl_contributor_civil_status": "Contributor's Civil Status",
  "lbl_num_marriages": "Number of Marriages Had?",
  "lbl_marriage_record_contributor": "Marriage Record (Deceased Contributor)",
  "msg_marriage_mapped_contributor": "This marriage is structurally mapped to the deceased Contributor. Civil inputs explicitly bypassed to prevent redundant data entry.",
  "lbl_specify_contributor": "Specify the corresponding Contributor's Marriage details:",
  "opt_sync_marriage": "Sync with Contributor Marriage",
  "msg_data_persistently_mapped": "Data persistently mapped from Contributor Marriage 1.",
  "lbl_marriage_record_n": "Marriage Record",
  "lbl_marriage_law": "Marriage Law",
  "opt_general": "General",
  "opt_kandyan": "Kandyan",
  "opt_muslim": "Muslim",
  "lbl_marriage_date": "Marriage Date",
  "lbl_cert_number": "Certificate Number",
  "lbl_reg_division": "Registrar's Division",
  "msg_warning_marriage_after_ret": "Warning: This marriage logically occurred *after* the contributor's retirement date",
  "lbl_spouse_civil_info": "Spouse Civil Information",
  "lbl_spouse_name": "Spouse Name",
  "lbl_spouse_nic": "Spouse NIC",
  "lbl_spouse_dob": "Spouse Date of Birth",
  "lbl_spouse_gov_emp": "Spouse a Govt Employee?",
  "lbl_wop_reg_no": "W&OP Reg No.",
  "lbl_spouse_gov_pen": "Spouse a Govt Pensioner?",
  "lbl_spouse_pen_no": "Spouse's Own Pension No.",
  "lbl_claiming_another_wop": "Claiming another W&OP?",
  "lbl_exist_wop_no": "Existing W&OP Pen No.",
  "lbl_current_legal_status": "Current Legal Marriage Status / Termination Method",
  "opt_active_legal": "Active Legal Marriage",
  "opt_ended_demise": "Ended: Demise of Spouse",
  "opt_legally_divorced": "Legally Divorced",
  "opt_separated": "Separated",
  "opt_void": "Void",
  "lbl_decree_nisi": "Decree Nisi (Conditional) Date",
  "lbl_decree_absolute": "Decree Absolute (Final) Date",
  "lbl_sep_date": "Official Date of Separation",
  "msg_sep_warning": "Warning: Separation does not legally terminate the marriage timeline! It is deemed an active negative condition that explicitly requires Director General Special Approval and forcibly blocks subsequent lawful marriages.",
  "lbl_court_order_date": "Date of Court Order",
  "lbl_court_name": "Court Name",
  "lbl_case_number": "Case Number",
  "lbl_spouse_living": "Is this Spouse physically living?",
  "opt_alive": "Alive",
  "opt_deceased": "Deceased",
  "lbl_has_remarried": "Has this Widow/Widower Remarried?",
  "lbl_remarriage_date": "Exact Date of Remarriage",
  "lbl_apply_50_wop": "Did they formally apply for the 50% W&OP pension before 2014.12.31?",
  "lbl_absolute_dod": "Absolute Date of Death",
  "lbl_death_cert_no": "Death Cert No.",
  "lbl_children_tied": "Children tied to Marriage",
  "lbl_no_children": "No. of Children Born to this Marriage",
  "lbl_child_details": "Child Details",
  "lbl_auto_age": "Auto Age: ",
  "msg_child_16_nic": "Child is ≥ 16 years. NIC Required:",
  "lbl_child_disabled": "Child is Permanently Disabled (Incapable of supporting oneself)",
  "lbl_child_dis_before_26": "Disability occurred natively since birth or strictly prior to completing age 26",
  "lbl_child_health_307": "Produced to Medical Board via Health 307 Report",
  "lbl_child_med_board": "Examined & Certified by the Main Medical Board",
  "lbl_med_board_date": "3-Member Consultants Panel Decision Date",
  "lbl_dg_approval_needed": "DG Pensions Special Approval Required",
  "msg_dg_approval_needed": "One or more marriages failed to complete a 1-year duration and yielded no children. Special approval from the Director General of Pensions must be obtained and validated to render eligibility.",
  "btn_next_section_e": "Next: Section E",
  "err_no_wop_benefit": "Sorry, No W&OP benefit for the Spouse! The contributor is documented as strictly holding zero legal marriages.",
  "err_fatal_marriage_post_ret": "Marriage fundamentally occurred post-retirement. Spouses legally married after the contributor's retirement are strictly ineligible for W&OP.",
  "err_numeric_required": "Numeric characters strictly required."
};

const secD_si = {
  "section_d_title": "D කොටස: දායකයාගේ සිවිල් තත්ත්වය",
  "lbl_contributor_civil_status": "දායකයාගේ සිවිල් තත්ත්වය",
  "lbl_num_marriages": "සිදුවී ඇති විවාහ සංඛ්‍යාව?",
  "lbl_marriage_record_contributor": "විවාහ වාර්තාව (මියගිය දායකයා)",
  "msg_marriage_mapped_contributor": "මෙම විවාහය ව්‍යුහාත්මකව මියගිය දායකයාට අනුරූප වේ. දත්ත දෙවරක් ඇතුළත් කිරීම වැළැක්වීම සඳහා සිවිල් තොරතුරු ස්වයංක්‍රීයව බැහැර කර ඇත.",
  "lbl_specify_contributor": "දායකයාගේ අදාළ විවාහ තොරතුරු සඳහන් කරන්න:",
  "opt_sync_marriage": "දායකයාගේ විවාහය සමග සමමුහුර්ත කරන්න",
  "msg_data_persistently_mapped": "දත්ත ස්ථිරවම දායකයාගේ 1 වන විවාහයෙන් සිතියම්ගත කර ඇත.",
  "lbl_marriage_record_n": "විවාහ වාර්තාව",
  "lbl_marriage_law": "විවාහ නීතිය",
  "opt_general": "සාමාන්‍ය",
  "opt_kandyan": "උඩරට",
  "opt_muslim": "මුස්ලිම්",
  "lbl_marriage_date": "විවාහ වූ දිනය",
  "lbl_cert_number": "සහතික අංකය",
  "lbl_reg_division": "රෙජිස්ට්‍රාර් කොට්ඨාශය",
  "msg_warning_marriage_after_ret": "අවවාදයයි: මෙම විවාහය තර්කානුකූලව දායකයාගේ විශ්‍රාම දිනයෙන් පසුව සිදුවී ඇත",
  "lbl_spouse_civil_info": "සහකරුගේ/සහකාරියගේ සිවිල් තොරතුරු",
  "lbl_spouse_name": "නම",
  "lbl_spouse_nic": "ජා.හැ.පත අංකය",
  "lbl_spouse_dob": "උපන් දිනය",
  "lbl_spouse_gov_emp": "රජයේ සේවකයෙක්ද?",
  "lbl_wop_reg_no": "W&OP ලියාපදිංචි අංකය",
  "lbl_spouse_gov_pen": "රජයේ විශ්‍රාමිකයෙක්ද?",
  "lbl_spouse_pen_no": "තම විශ්‍රාම වැටුප් අංකය",
  "lbl_claiming_another_wop": "වෙනත් W&OP ප්‍රතිලාභයක් ලබා ගන්නේද?",
  "lbl_exist_wop_no": "දැනට පවතින W&OP විශ්‍රාම වැටුප් අංකය",
  "lbl_current_legal_status": "වත්මන් නීත්‍යානුකූල විවාහ තත්ත්වය / අවසන් කිරීමේ ක්‍රමය",
  "opt_active_legal": "සක්‍රීය නීත්‍යානුකූල විවාහය",
  "opt_ended_demise": "අවසන් විය: සහකරුගේ/සහකාරියගේ මරණය",
  "opt_legally_divorced": "නීත්‍යානුකූලව දික්කසාද වී ඇත",
  "opt_separated": "වෙන්වී ඇත",
  "opt_void": "අවලංගුයි",
  "lbl_decree_nisi": "අතුරු තහනම් (කොන්දේසි සහිත) නියෝගයේ දිනය",
  "lbl_decree_absolute": "පරම (අවසාන) නියෝගයේ දිනය",
  "lbl_sep_date": "නිල වශයෙන් වෙන්වීමේ දිනය",
  "msg_sep_warning": "අවවාදයයි: වෙන්වීම විවාහය නීත්‍යානුකූලව අවසන් නොකරයි! එය විශ්‍රාම වැටුප් අධ්‍යක්ෂ ජනරාල්වරයාගේ විශේෂ අනුමැතිය අවශ්‍ය වන අතර, පසුකාලීන නීත්‍යානුකූල විවාහයන් බලහත්කාරයෙන් අවහිර කරනු ලබයි.",
  "lbl_court_order_date": "උසාවි නියෝගයේ දිනය",
  "lbl_court_name": "උසාවියේ නම",
  "lbl_case_number": "නඩු අංකය",
  "lbl_spouse_living": "මෙම සහකරු/සහකාරිය භෞතිකව ජීවතුන් අතරද?",
  "opt_alive": "ජීවතුන් අතර",
  "opt_deceased": "මියගොස් ඇත",
  "lbl_has_remarried": "මෙම වැන්දඹුව/වැන්දඹු පුරුෂයා නැවත විවාහ වී තිබේද?",
  "lbl_remarriage_date": "නැවත විවාහ වූ නිශ්චිත දිනය",
  "lbl_apply_50_wop": "ඔවුන් 2014.12.31 ට පෙර 50% W&OP විශ්‍රාම වැටුප සඳහා විධිමත්ව අයදුම් කළාද?",
  "lbl_absolute_dod": "නිශ්චිත මරණ දිනය",
  "lbl_death_cert_no": "මරණ සහතික අංකය",
  "lbl_children_tied": "මෙම විවාහයට අදාළ දරුවන්",
  "lbl_no_children": "මෙම විවාහයෙන් උපන් දරුවන් සංඛ්‍යාව",
  "lbl_child_details": "දරුවාගේ තොරතුරු",
  "lbl_auto_age": "ස්වයංක්‍රීය වයස: ",
  "msg_child_16_nic": "දරුවාට වයස අවුරුදු 16 හෝ ඊට වැඩිය. ජා.හැ.පත අත්‍යවශ්‍යයි:",
  "lbl_child_disabled": "දරුවා ස්ථිරවම ආබාධිතයි (තමාටම සහාය වීමට හැකියාවක් නොමැත)",
  "lbl_child_dis_before_26": "ආබාධිත තත්ත්වය උපතේ සිටම හෝ වයස අවුරුදු 26 සම්පූර්ණ වීමට පෙර සිදුවී ඇත",
  "lbl_child_health_307": "Health 307 වාර්තාව හරහා වෛද්‍ය මණ්ඩලය වෙත ඉදිරිපත් කර ඇත",
  "lbl_child_med_board": "ප්‍රධාන වෛද්‍ය මණ්ඩලය මගින් පරීක්ෂා කර සහතික කර ඇත",
  "lbl_med_board_date": "ත්‍රිපුද්ගල උපදේශක මණ්ඩලයේ තීරණ දිනය",
  "lbl_dg_approval_needed": "විශ්‍රාම වැටුප් අධ්‍යක්ෂ ජනරාල්ගේ විශේෂ අනුමැතිය අවශ්‍යයි",
  "msg_dg_approval_needed": "එක් විවාහයක් හෝ ඊට වැඩි ගණනක් වසර 1ක කාල සීමාවක් සම්පූර්ණ කිරීමට අපොහොසත් වී ඇති අතර දරුවන් නොමැත. සුදුසුකම් ලැබීමට විශ්‍රාම වැටුප් අධ්‍යක්ෂ ජනරාල්වරයාගෙන් විශේෂ අනුමැතිය ලබා ගත යුතුය.",
  "btn_next_section_e": "ඊළඟ: E කොටස",
  "err_no_wop_benefit": "සමාවන්න, සහකරුට/සහකාරියට W&OP ප්‍රතිලාභයක් නොමැත! දායකයාට නිත්‍යානුකූල විවාහ නොමැති බවට ලේඛනගත කර ඇත.",
  "err_fatal_marriage_post_ret": "විවාහය විශ්‍රාම ගැනීමෙන් පසුව සිදුවී ඇත. දායකයා විශ්‍රාම ගැනීමෙන් පසු නීත්‍යානුකූලව විවාහ වූ සහකරුවන් W&OP සඳහා සුදුසුකම් නොලබයි.",
  "err_numeric_required": "සංඛ්‍යාත්මක අක්ෂර අත්‍යවශ්‍යයි."
};

const secD_ta = {
  "section_d_title": "பகுதி D: பங்களிப்பாளரின் சிவில் நிலை",
  "lbl_contributor_civil_status": "பங்களிப்பாளரின் சிவில் நிலை",
  "lbl_num_marriages": "எத்தனை திருமணங்கள் நடந்தன?",
  "lbl_marriage_record_contributor": "திருமணப் பதிவு (இறந்த பங்களிப்பாளர்)",
  "msg_marriage_mapped_contributor": "இந்தத் திருமணம் இறந்த பங்களிப்பாளருடன் இணைக்கப்பட்டுள்ளது. தேவையற்ற தரவு உள்ளீட்டைத் தடுக்க சிவில் உள்ளீடுகள் தவிர்க்கப்பட்டுள்ளன.",
  "lbl_specify_contributor": "பங்களிப்பாளரின் திருமண விவரங்களைக் குறிப்பிடவும்:",
  "opt_sync_marriage": "பங்களிப்பாளர் திருமணத்துடன் ஒத்திசைக்கவும்",
  "msg_data_persistently_mapped": "தரவுகள் பங்களிப்பாளர் திருமணம் 1 இலிருந்து பெறப்பட்டுள்ளன.",
  "lbl_marriage_record_n": "திருமணப் பதிவு",
  "lbl_marriage_law": "திருமணச் சட்டம்",
  "opt_general": "பொது",
  "opt_kandyan": "கண்டியன்",
  "opt_muslim": "முஸ்லிம்",
  "lbl_marriage_date": "திருமணத் தேதி",
  "lbl_cert_number": "சான்றிதழ் எண்",
  "lbl_reg_division": "பதிவாளர் பிரிவு",
  "msg_warning_marriage_after_ret": "எச்சரிக்கை: இந்தத் திருமணம் பங்களிப்பாளரின் ஓய்வு தேதிக்குப் பிறகு நிகழ்ந்துள்ளது",
  "lbl_spouse_civil_info": "துணைவர் சிவில் தகவல்",
  "lbl_spouse_name": "துணைவர் பெயர்",
  "lbl_spouse_nic": "துணைவர் தே.அ.அட்டை",
  "lbl_spouse_dob": "பிறந்த தேதி",
  "lbl_spouse_gov_emp": "அரசு ஊழியரா?",
  "lbl_wop_reg_no": "W&OP பதிவு எண்",
  "lbl_spouse_gov_pen": "அரசு ஓய்வூதியரா?",
  "lbl_spouse_pen_no": "ஓய்வூதிய எண்",
  "lbl_claiming_another_wop": "வேறு W&OP பெறுகிறாரா?",
  "lbl_exist_wop_no": "தற்போதுள்ள W&OP எண்",
  "lbl_current_legal_status": "தற்போதைய சட்டப்பூர்வ திருமண நிலை",
  "opt_active_legal": "செயலில் உள்ள திருமணம்",
  "opt_ended_demise": "முடிந்தது: துணைவர் இறப்பு",
  "opt_legally_divorced": "விவாகரத்து செய்யப்பட்டது",
  "opt_separated": "பிரிந்துள்ளனர்",
  "opt_void": "செல்லாது",
  "lbl_decree_nisi": "இடைக்கால (நிபந்தனை) உத்தரவு தேதி",
  "lbl_decree_absolute": "இறுதி உத்தரவு தேதி",
  "lbl_sep_date": "அதிகாரப்பூர்வ பிரிவினை தேதி",
  "msg_sep_warning": "எச்சரிக்கை: பிரிவினை திருமணத்தை சட்டப்பூர்வமாக முடிக்காது! ஓய்வூதிய பணிப்பாளர் நாயகத்தின் சிறப்பு அனுமதி தேவை.",
  "lbl_court_order_date": "நீதிமன்ற உத்தரவு தேதி",
  "lbl_court_name": "நீதிமன்றத்தின் பெயர்",
  "lbl_case_number": "வழக்கு எண்",
  "lbl_spouse_living": "துணைவர் உயிருடன் இருக்கிறாரா?",
  "opt_alive": "உயிருடன்",
  "opt_deceased": "இறந்துவிட்டார்",
  "lbl_has_remarried": "மறுமணம் செய்துள்ளாரா?",
  "lbl_remarriage_date": "மறுமணத் தேதி",
  "lbl_apply_50_wop": "2014.12.31 க்கு முன் 50% W&OP க்கு விண்ணப்பித்தார்களா?",
  "lbl_absolute_dod": "இறந்த தேதி",
  "lbl_death_cert_no": "இறப்பு சான்றிதழ் எண்",
  "lbl_children_tied": "இந்த திருமணத்தின் குழந்தைகள்",
  "lbl_no_children": "இந்த திருமணத்தில் பிறந்த குழந்தைகளின் எண்ணிக்கை",
  "lbl_child_details": "குழந்தை விவரங்கள்",
  "lbl_auto_age": "தானியங்கி வயது: ",
  "msg_child_16_nic": "குழந்தைக்கு 16 அல்லது அதற்கு மேற்பட்ட வயது. தே.அ.அட்டை தேவை:",
  "lbl_child_disabled": "நிரந்தர குறைபாடுடைய குழந்தை (தன்னைத்தானே ஆதரிக்க முடியாதவர்)",
  "lbl_child_dis_before_26": "பிறப்பிலிருந்தே அல்லது 26 வயதுக்கு முன் குறைபாடு ஏற்பட்டது",
  "lbl_child_health_307": "Health 307 அறிக்கை மருத்துவ குழுவிற்கு சமர்ப்பிக்கப்பட்டது",
  "lbl_child_med_board": "பிரதான மருத்துவ குழுவினால் சான்றளிக்கப்பட்டது",
  "lbl_med_board_date": "3-உறுப்பினர் குழுவின் முடிவு தேதி",
  "lbl_dg_approval_needed": "ஓய்வூதிய பணிப்பாளர் நாயகத்தின் அனுமதி தேவை",
  "msg_dg_approval_needed": "ஒரு திருமணம் 1 வருடத்தை நிறைவு செய்யவில்லை மற்றும் குழந்தைகள் இல்லை. தகுதியைப் பெற ஓய்வூதிய பணிப்பாளர் நாயகத்தின் சிறப்பு அனுமதி பெறப்பட வேண்டும்.",
  "btn_next_section_e": "அடுத்து: பகுதி E",
  "err_no_wop_benefit": "மன்னிக்கவும், W&OP நன்மை இல்லை! பங்களிப்பாளருக்கு சட்டபூர்வமான திருமணங்கள் ஏதும் இல்லை என ஆவணப்படுத்தப்பட்டுள்ளது.",
  "err_fatal_marriage_post_ret": "திருமணம் ஓய்வுக்குப் பிறகு நடந்துள்ளது. ஓய்வுக்குப் பிறகு நடந்த திருமணங்களுக்கு W&OP கிடைக்காது.",
  "err_numeric_required": "எண்கள் மட்டுமே தேவை."
};

const newData = {
  en: { ...secD_en },
  si: { ...secD_si },
  ta: { ...secD_ta }
};

['en', 'si', 'ta'].forEach(lang => {
  const file = `./src/locales/${lang}.json`;
  let existing = {};
  if(fs.existsSync(file)) {
      existing = JSON.parse(fs.readFileSync(file, 'utf8'));
  }
  const updated = { ...existing, ...newData[lang] };
  fs.writeFileSync(file, JSON.stringify(updated, null, 2));
});
