const fs = require('fs');

const p1a_en = {
  "part1a_title": "Part 1A: Check Basic Info",
  "err_global_format": "Format Error: Please review the RED bordered fields to resolve structural errors before proceeding.",
  "err_global_nic_format": "Format Error: ",
  "err_invalid_lifecycle": "Invalid Life Cycle: Death date cannot be physically recorded prior to the birth date.",
  "err_statutory_65": "Invalid Context: The contributor is declared as Deceased while in Active Service, but the recorded Age at Death exceeds the strict statutory maximum service age limit of 65 years.",
  "err_missing_active_4m": "Eligibility Denied: For active service Missing Persons, a statutory waiting period of strictly 4 months from the Police Complaint must chronologically elapse.",
  "err_missing_retired_12m": "Eligibility Denied: For retired Missing Persons, a statutory waiting period of strictly 12 months from the Police Complaint must chronologically elapse.",
  "lbl_deceased_status": "Deceased Status:",
  "opt_pensioner": "Pensioner",
  "opt_before_retirement": "Before Retirement",
  "lbl_is_missing": "Is Contributor a Missing Person?",
  "lbl_name_nic": "Name as per NIC/SLNIC",
  "lbl_gender": "Gender",
  "opt_male": "Male",
  "opt_female": "Female",
  "lbl_dob": "Date of Birth",
  "lbl_nic": "NIC / SLNIC Number",
  "lbl_dod": "Date of Death",
  "lbl_date_police": "Date of Police Complaint",
  "msg_waiting_period_validated": "Waiting period statically validated automatically.",
  "lbl_dor": "Date of Retirement",
  "btn_next_section_a": "Next: Section A",
  "btn_back": "Back"
};

const secA_en = {
  "section_a_title": "Section A: Appointment Checks",
  "lbl_doa": "Date of Appointment",
  "lbl_is_45": "Is target exact age > 45?",
  "msg_yes": "YES",
  "msg_no": "NO",
  "msg_appointee_gt_45": "Appointee is strictly >45 years. Requires Cabinet/Special Approval Date.",
  "msg_no_approval_invalid": "If no approval is obtained, this constitutes an invalid appointment.",
  "lbl_appt_permanent": "Was the appointment permanent and with pension?",
  "opt_yes": "Yes",
  "opt_no_temp": "No (Non-Pensionable / Temporary / Casual)",
  "lbl_terrorist_exemption": "Terrorist Reason Exemption",
  "msg_died_terrorist": "Did the contributor explicitly die due to a terrorist reason while in active service?",
  "lbl_female_validations": "Female Officer Specific Validations",
  "lbl_appt_after_1983": "Was appointment after 1983.08.01?",
  "opt_yes_valid": "Yes (Valid)",
  "lbl_consent_wop": "Given consent to contribute to W&OP while in Service?",
  "opt_select": "Select Option...",
  "opt_yes_before_2014": "No, but gave consent before 2014.12.31",
  "opt_yes_evidence": "No records, but has evidence of contribution",
  "opt_no_reluctant": "Had she given her Reluctance to contribute W&OP?",
  "btn_next_section_b": "Next: Section B",
  "err_female_reluctant": "Not Eligible for W&OP Benefits due to active reluctance recorded on file preventing valid contribution.",
  "err_under_18": "Statutory Application Voided: The individual was officially under 18 years of age at the time of specific Government Appointment. Minimum age requirements strictly breached.",
  "err_no_cabinet_approval": "Not Eligible for W&OP Benefits. The Officer was strictly >45 at appointment but failed to supply the mandatory Cabinet Special Approval Date.",
  "err_fill_female_consent": "Please fill in female consent rules.",
  "err_not_permanent": "Not Eligible for W&OP Benefits. The eligibility exists only for permanent and pensionable appointees natively, unless specifically classified as an active-service Terrorist casualty."
};

const secBC_en = {
  "section_b_c_title": "Section B & C",
  "lbl_reg_term": "Registration & Termination Validation",
  "lbl_is_wop_reg": "Is the Contributor Registered for W&OP?",
  "err_not_reg_wop": "Please Register for W&OP Membership. Contact the Employee's (Contributor's) Last Working Place.",
  "lbl_wop_no": "W&OP Member Number",
  "lbl_contributions_recovered": "Have contribution deductions been recovered for the complete reckonable service period?",
  "err_contributions_unrecovered": "Not Eligible for W&OP Benefits until W&OP contributions are completely recovered for the total reckonable service period.",
  "lbl_sec_c_term": "Section C: Termination of Service",
  "lbl_pensioner_details": "Pensioner Details",
  "lbl_retired_date": "Retired Date",
  "lbl_pension_commenced": "Have Pension Payments Commenced?",
  "lbl_last_pension_date": "Last Pension Payment Date",
  "lbl_non_pensioner_details": "Non-Pensioner (In-Service) Details",
  "lbl_loss_of_pension": "Did the contributor's service end due to Vacation of Post / Dismissal / Resignation (Loss of Pension) prior to death?",
  "lbl_loss_date": "Date of Vacation / Dismissal / Resignation",
  "lbl_loss_reason": "Exact Reason",
  "opt_vop": "Vacation of Post",
  "opt_dismissal": "Dismissal",
  "opt_resignation": "Resignation",
  "lbl_uncountable": "Uncountable Service Periods (No Pay / Half Pay)",
  "btn_add_period": "Add Period",
  "lbl_from": "From",
  "lbl_to": "To",
  "lbl_reason": "Reason",
  "btn_remove": "Remove",
  "lbl_reckonable_calc": "Live Reckonable Service Engine",
  "btn_next_section_d": "Next: Section D"
};

const p1a_si = {
  "part1a_title": "1A කොටස: මූලික තොරතුරු පරීක්ෂා කිරීම",
  "err_global_format": "ආකෘති දෝෂය: කරුණාකර ඉදිරියට යාමට පෙර රතු මායිම් ඇති ක්ෂේත්‍ර සමාලෝචනය කරන්න.",
  "err_global_nic_format": "ආකෘති දෝෂය: ",
  "err_invalid_lifecycle": "අවලංගු ජීවන චක්‍රය: මරණ දිනය උපන් දිනයට පෙර විය නොහැක.",
  "err_statutory_65": "අවලංගු සන්දර්භය: දායකයා සක්‍රීය සේවයේ මියගිය බව ප්‍රකාශ කර ඇත, නමුත් මිය යන විට වයස උපරිම සේවා වයස් සීමාව වන අවුරුදු 65 ඉක්මවයි.",
  "err_missing_active_4m": "සුදුසුකම් ප්‍රතික්ෂේප කෙරිණි: සක්‍රීය සේවයේ අතුරුදහන් වූ පුද්ගලයින් සඳහා, පොලිස් පැමිණිල්ලෙන් පසු මාස 4ක නීත්‍යානුකූල රැඳී සිටීමේ කාලයක් අනිවාර්යයෙන් ගතවිය යුතුය.",
  "err_missing_retired_12m": "සුදුසුකම් ප්‍රතික්ෂේප කෙරිණි: විශ්‍රාමික අතුරුදහන් වූ පුද්ගලයින් සඳහා, පොලිස් පැමිණිල්ලෙන් පසු මාස 12ක නීත්‍යානුකූල රැඳී සිටීමේ කාලයක් අනිවාර්යයෙන් ගතවිය යුතුය.",
  "lbl_deceased_status": "මියගිය තත්ත්වය:",
  "opt_pensioner": "විශ්‍රාමික",
  "opt_before_retirement": "විශ්‍රාම යාමට පෙර",
  "lbl_is_missing": "දායකයා අතුරුදහන් වූ පුද්ගලයෙක්ද?",
  "lbl_name_nic": "ජා.හැ.පත අනුව නම",
  "lbl_gender": "ස්ත්‍රී/පුරුෂ භාවය",
  "opt_male": "පුරුෂ",
  "opt_female": "ස්ත්‍රී",
  "lbl_dob": "උපන් දිනය",
  "lbl_nic": "ජා.හැ.ප අංකය",
  "lbl_dod": "මියගිය දිනය",
  "lbl_date_police": "පොලිස් පැමිණිල්ලේ දිනය",
  "msg_waiting_period_validated": "රැඳී සිටීමේ කාලය ස්වයංක්‍රීයව තහවුරු විය.",
  "lbl_dor": "විශ්‍රාම ගිය දිනය",
  "btn_next_section_a": "ඊළඟ: A කොටස",
  "btn_back": "ආපසු"
};

const secA_si = {
  "section_a_title": "A කොටස: පත්වීම් පරීක්ෂාව",
  "lbl_doa": "පත්වීමේ දිනය",
  "lbl_is_45": "වයස අවුරුදු 45 ට වැඩිද?",
  "msg_yes": "ඔව්",
  "msg_no": "නැත",
  "msg_appointee_gt_45": "පත්වීම් ලාභියාට වයස 45ට වැඩියි. කැබිනට්/විශේෂ අනුමත දිනයක් අවශ්‍යයි.",
  "msg_no_approval_invalid": "අනුමැතියක් ලබාගෙන නොමැති නම්, මෙය අවලංගු පත්වීමක් වේ.",
  "lbl_appt_permanent": "පත්වීම ස්ථිර සහ විශ්‍රාම වැටුප් සහිතද?",
  "opt_yes": "ඔව්",
  "opt_no_temp": "නැත (විශ්‍රාම වැටුප් රහිත / තාවකාලික / අනියම්)",
  "lbl_terrorist_exemption": "ත්‍රස්තවාදී හේතු නිදහස් කිරීම",
  "msg_died_terrorist": "දායකයා සක්‍රීය සේවයේ යෙදී සිටියදී ත්‍රස්තවාදී ක්‍රියාවක් හේතුවෙන් මිය ගියේද?",
  "lbl_female_validations": "කාන්තා නිලධාරි විශේෂිත තහවුරු කිරීම්",
  "lbl_appt_after_1983": "පත්වීම 1983.08.01 න් පසුවද?",
  "opt_yes_valid": "ඔව් (වලංගුයි)",
  "lbl_consent_wop": "සේවයේ යෙදී සිටියදී W&OP වෙත දායක වීමට කැමැත්ත ලබා දී තිබේද?",
  "opt_select": "විකල්පයක් තෝරන්න...",
  "opt_yes_before_2014": "නැත, නමුත් 2014.12.31 ට පෙර කැමැත්ත ලබා දී ඇත",
  "opt_yes_evidence": "වාර්තා නොමැත, නමුත් දායකත්වය පිළිබඳ සාක්ෂි ඇත",
  "opt_no_reluctant": "W&OP දායක වීමට ඇය සිය අකමැත්ත ලබා දී තිබේද?",
  "btn_next_section_b": "ඊළඟ: B කොටස",
  "err_female_reluctant": "W&OP ප්‍රතිලාභ සඳහා සුදුසුකම් නොලබයි. දායක වීමට අකමැත්ත ලිඛිතව ප්‍රකාශ කර ඇත.",
  "err_under_18": "අයදුම්පත අවලංගුයි: රජයේ පත්වීම ලබා දෙන අවස්ථාවේදී නිල වශයෙන් වයස අවුරුදු 18 ට අඩු විය.",
  "err_no_cabinet_approval": "W&OP සඳහා සුදුසුකම් නොලබයි. පත්වීමේදී වයස 45ට වැඩි වූ නමුත් විශේෂ කැබිනට් අනුමැතිය ලබා දී නොමැත.",
  "err_fill_female_consent": "කරුණාකර කාන්තා කැමැත්ත පිරවීම සම්පූර්ණ කරන්න.",
  "err_not_permanent": "W&OP සඳහා සුදුසුකම් නොලබයි. සක්‍රීය සේවයේ ත්‍රස්තවාදී මරණයක් ලෙස වර්ගීකරණය කර නොමැති නම්, සුදුසුකම් ලබන්නේ ස්ථිර සහ විශ්‍රාම වැටුප් සහිත පත්වීම් ලාභීන් පමණි."
};

const secBC_si = {
  "section_b_c_title": "B සහ C කොටස",
  "lbl_reg_term": "ලියාපදිංචිය සහ සේවා අවසන් කිරීම තහවුරු කිරීම",
  "lbl_is_wop_reg": "දායකයා W&OP සඳහා ලියාපදිංචි වී තිබේද?",
  "err_not_reg_wop": "කරුණාකර W&OP සාමාජිකත්වය සඳහා ලියාපදිංචි වන්න. සේවකයාගේ අවසන් වරට සේවය කළ ස්ථානය අමතන්න.",
  "lbl_wop_no": "W&OP සාමාජික අංකය",
  "lbl_contributions_recovered": "සම්පූර්ණ ගණන් ගත හැකි සේවා කාලය සඳහා දායක මුදල් අඩු කිරීම් අයකරගෙන තිබේද?",
  "err_contributions_unrecovered": "සම්පූර්ණ ගණන් ගත හැකි සේවා කාලය සඳහා W&OP දායක මුදල් සම්පූර්ණයෙන්ම අයකර ගන්නා තුරු W&OP ප්‍රතිලාභ සඳහා සුදුසුකම් නොලබයි.",
  "lbl_sec_c_term": "C කොටස: සේවය අවසන් කිරීම",
  "lbl_pensioner_details": "විශ්‍රාමික තොරතුරු",
  "lbl_retired_date": "විශ්‍රාම ගිය දිනය",
  "lbl_pension_commenced": "විශ්‍රාම වැටුප් ගෙවීම් ආරම්භ වී තිබේද?",
  "lbl_last_pension_date": "අවසන් වරට විශ්‍රාම වැටුප් ගෙවූ දිනය",
  "lbl_non_pensioner_details": "විශ්‍රාමික නොවන (සක්‍රීය සේවයේ) තොරතුරු",
  "lbl_loss_of_pension": "මරණයට පෙර සේවය හැර යාම / සේවයෙන් පහ කිරීම / ඉල්ලා අස්වීම (විශ්‍රාම වැටුප අහිමි වීම) හේතුවෙන් දායකයාගේ සේවය අවසන් වූයේද?",
  "lbl_loss_date": "සේවය හැර ගිය / පහ කළ / ඉල්ලා අස් වූ දිනය",
  "lbl_loss_reason": "නිශ්චිත හේතුව",
  "opt_vop": "සේවය හැර යාම (VOP)",
  "opt_dismissal": "සේවයෙන් පහ කිරීම",
  "opt_resignation": "ඉල්ලා අස්වීම",
  "lbl_uncountable": "ගණන් ගත නොහැකි සේවා කාලයන් (වැටුප් රහිත / අර්ධ වැටුප්)",
  "btn_add_period": "කාල සීමාවක් එක් කරන්න",
  "lbl_from": "සිට",
  "lbl_to": "දක්වා",
  "lbl_reason": "හේතුව",
  "btn_remove": "ඉවත් කරන්න",
  "lbl_reckonable_calc": "ගණන් ගත හැකි සේවා කාලය (සජීවී)",
  "btn_next_section_d": "ඊළඟ: D කොටස"
};

const p1a_ta = {
  "part1a_title": "பகுதி 1A: அடிப்படைத் தகவல்களைச் சரிபார்க்கவும்",
  "err_global_format": "வடிவமைப்பு பிழை: தொடர்வதற்கு முன் சிவப்பு நிறத்தில் உள்ள பிழைகளை சரிசெய்யவும்.",
  "err_global_nic_format": "வடிவமைப்பு பிழை: ",
  "err_invalid_lifecycle": "தவறான வாழ்க்கை சுழற்சி: பிறந்த தேதிக்கு முன்பு மரண தேதி இருக்க முடியாது.",
  "err_statutory_65": "தவறான சூழல்: சேவையில் இருக்கும்போது இறந்ததாக அறிவிக்கப்பட்டுள்ளது, ஆனால் அதிகபட்ச சேவை வயதான 65 ஆண்டுகளை மீறுகிறது.",
  "err_missing_active_4m": "தகுதி நிராகரிக்கப்பட்டது: சேவையில் காணாமல் போனவர்களுக்கு, பொலிஸ் புகாரிலிருந்து 4 மாதங்கள் காத்திருப்பு காலம் அவசியம்.",
  "err_missing_retired_12m": "தகுதி நிராகரிக்கப்பட்டது: ஓய்வுபெற்ற காணாமல் போனவர்களுக்கு, பொலிஸ் புகாரிலிருந்து 12 மாதங்கள் காத்திருப்பு காலம் அவசியம்.",
  "lbl_deceased_status": "இறந்த நிலை:",
  "opt_pensioner": "ஓய்வூதியர்",
  "opt_before_retirement": "ஓய்வுக்கு முன்",
  "lbl_is_missing": "பங்களிப்பாளர் காணாமல் போனவரா?",
  "lbl_name_nic": "தே.அ.அட்டைப்படி பெயர்",
  "lbl_gender": "பாலினம்",
  "opt_male": "ஆண்",
  "opt_female": "பெண்",
  "lbl_dob": "பிறந்த தேதி",
  "lbl_nic": "தே.அ.அட்டை எண்",
  "lbl_dod": "இறந்த தேதி",
  "lbl_date_police": "பொலிஸ் புகார் தேதி",
  "msg_waiting_period_validated": "காத்திருப்பு காலம் தானாகவே சரிபார்க்கப்பட்டது.",
  "lbl_dor": "ஓய்வுபெற்ற தேதி",
  "btn_next_section_a": "அடுத்து: பகுதி A",
  "btn_back": "திரும்பு"
};

const secA_ta = {
  "section_a_title": "பகுதி A: நியமனம் சரிபார்ப்பு",
  "lbl_doa": "நியமனம் செய்யப்பட்ட தேதி",
  "lbl_is_45": "வயது 45-ஐ விட அதிகமா?",
  "msg_yes": "ஆம்",
  "msg_no": "இல்லை",
  "msg_appointee_gt_45": "நியமனம் பெற்றவரின் வயது 45க்கு மேல். அமைச்சரவை/விசேட அனுமதி தேதி தேவை.",
  "msg_no_approval_invalid": "அனுமதி பெறப்படாவிட்டால், இது செல்லுபடியற்ற நியமனமாக கருதப்படும்.",
  "lbl_appt_permanent": "நியமனம் நிரந்தரமானதா மற்றும் ஓய்வூதியம் உள்ளதா?",
  "opt_yes": "ஆம்",
  "opt_no_temp": "இல்லை (ஓய்வூதியமற்ற / தற்காலிக / சாதாரண)",
  "lbl_terrorist_exemption": "பயங்கரவாத காரணங்களுக்கான விதிவிலக்கு",
  "msg_died_terrorist": "பங்களிப்பாளர் சேவையில் இருக்கும்போது பயங்கரவாத செயல்களால் இறந்தாரா?",
  "lbl_female_validations": "பெண் அதிகாரிக்கான சிறப்பு சரிபார்ப்புகள்",
  "lbl_appt_after_1983": "நியமனம் 1983.08.01 க்குப் பிறகா?",
  "opt_yes_valid": "ஆம் (செல்லுபடியாகும்)",
  "lbl_consent_wop": "சேவையில் இருக்கும்போது W&OP க்கு பங்களிக்க சம்மதம் தெரிவிக்கப்பட்டதா?",
  "opt_select": "விருப்பத்தைத் தேர்ந்தெடுக்கவும்...",
  "opt_yes_before_2014": "இல்லை, ஆனால் 2014.12.31 க்கு முன் சம்மதம் தெரிவித்தார்",
  "opt_yes_evidence": "பதிவுகள் இல்லை, ஆனால் பங்களிப்பிற்கான சான்றுகள் உள்ளன",
  "opt_no_reluctant": "W&OP க்கு பங்களிக்க அவர் தயக்கம் காட்டியிருந்தாரா?",
  "btn_next_section_b": "அடுத்து: பகுதி B",
  "err_female_reluctant": "W&OP க்கு பங்களிக்க அவர் பதிவு செய்த தயக்கம் காரணமாக தகுதியற்றவர்.",
  "err_under_18": "விண்ணப்பம் ரத்து செய்யப்பட்டது: நியமனத்தின் போது அதிகாரப்பூர்வமாக 18 வயதுக்குட்பட்டவர்.",
  "err_no_cabinet_approval": "W&OP க்கு தகுதியற்றவர். நியமனத்தில் 45 வயதுக்கு மேற்பட்டவர், ஆனால் அமைச்சரவை அனுமதி இல்லை.",
  "err_fill_female_consent": "பெண் அதிகாரி சம்மத விதிகளை நிரப்பவும்.",
  "err_not_permanent": "W&OP க்கு தகுதியற்றவர். நிரந்தரமான மற்றும் ஓய்வூதியமுள்ள நியமனம் பெற்றவர்களுக்கு மட்டுமே தகுதி உண்டு."
};

const secBC_ta = {
  "section_b_c_title": "பகுதி B மற்றும் C",
  "lbl_reg_term": "பதிவு மற்றும் சேவையை முடித்தல் சரிபார்ப்பு",
  "lbl_is_wop_reg": "பங்களிப்பாளர் W&OP க்கு பதிவு செய்யப்பட்டுள்ளாரா?",
  "err_not_reg_wop": "தயவுசெய்து W&OP உறுப்பினராக பதிவு செய்யவும். பணியாளரின் கடைசியாக பணிபுரிந்த இடத்தை தொடர்பு கொள்ளவும்.",
  "lbl_wop_no": "W&OP உறுப்பினர் எண்",
  "lbl_contributions_recovered": "முழு கணக்கிடக்கூடிய சேவை காலத்திற்கும் பங்களிப்பு பிடித்தங்கள் அறவிடப்பட்டுள்ளனவா?",
  "err_contributions_unrecovered": "முழு சேவை காலத்திற்கும் W&OP பங்களிப்புகள் முழுமையாக அறவிடப்படும் வரை நன்மைகளுக்கு தகுதியற்றவர்.",
  "lbl_sec_c_term": "பகுதி C: சேவையை முடித்தல்",
  "lbl_pensioner_details": "ஓய்வூதியர் விவரங்கள்",
  "lbl_retired_date": "ஓய்வுபெற்ற தேதி",
  "lbl_pension_commenced": "ஓய்வூதிய கொடுப்பனவுகள் ஆரம்பிக்கப்பட்டுள்ளனவா?",
  "lbl_last_pension_date": "கடைசியாக ஓய்வூதியம் வழங்கப்பட்ட தேதி",
  "lbl_non_pensioner_details": "ஓய்வூதியமற்ற (செயலில் உள்ள) விவரங்கள்",
  "lbl_loss_of_pension": "இறப்புக்கு முன் சேவையை விட்டு வெளியேறுதல் / பணிநீக்கம் / ராஜினாமா காரணமாக பங்களிப்பாளரின் சேவை முடிவடைந்ததா?",
  "lbl_loss_date": "வெளியேறிய / பணிநீக்கம் / ராஜினாமா தேதி",
  "lbl_loss_reason": "சரியான காரணம்",
  "opt_vop": "சேவையை விட்டு வெளியேறுதல் (VOP)",
  "opt_dismissal": "பணிநீக்கம்",
  "opt_resignation": "ராஜினாமா",
  "lbl_uncountable": "கணக்கிட முடியாத சேவை காலங்கள் (சம்பளமில்லாத / அரை சம்பளம்)",
  "btn_add_period": "காலத்தைச் சேர்",
  "lbl_from": "இருந்து",
  "lbl_to": "வரை",
  "lbl_reason": "காரணம்",
  "btn_remove": "அகற்று",
  "lbl_reckonable_calc": "கணக்கிடக்கூடிய சேவை காலம்",
  "btn_next_section_d": "அடுத்து: பகுதி D"
};

const newData = {
  en: { ...p1a_en, ...secA_en, ...secBC_en },
  si: { ...p1a_si, ...secA_si, ...secBC_si },
  ta: { ...p1a_ta, ...secA_ta, ...secBC_ta }
};

['en', 'si', 'ta'].forEach(lang => {
  const file = `./src/locales/${lang}.json`;
  let existing = {};
  if(fs.existsSync(file)) {
      existing = JSON.parse(fs.readFileSync(file, 'utf8'));
  }
  const updated = { ...existing, ...newData[lang] };
  fs.writeFileSync(file, JSON.stringify(updated, null, 2));
});
